apiVersion: batch/v1
kind: CronJob
metadata:
  name: hhb-nightly-alarms-check
  labels:
    name: hhb-nightly-alarms-check
spec:
  schedule: "0 3 * * *" # Every day at 3am
  concurrencyPolicy: Replace # Only one job at a time, replace the previous if it hasn't finished yet
  startingDeadlineSeconds: 3600 # Allow the job to start up to 1 hour late
  failedJobsHistoryLimit: 5 # Keep the last 5 failed jobs
  successfulJobsHistoryLimit: 1 # Keep only the last successful job
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: check-alarms
              image: backend
              imagePullPolicy: IfNotPresent
              env:
                - name: REQUIRE_AUTH
                  value: "0"
                - name: HHB_SERVICE_URL
                  value: "http://hhb-huishoudboekjeservice"
                - name: ORGANISATIE_SERVICE_URL
                  value: "http://hhb-organisatieservice"
                - name: TRANSACTIE_SERVICE_URL
                  value: "http://hhb-banktransactieservice"
                - name: GROOTBOEK_SERVICE_URL
                  value: "http://hhb-grootboekservice"
                - name: LOG_SERVICE_URL
                  value: "http://hhb-logservice"
                - name: POSTADRESSENSERVICE_URL
                  value: "http://hhb-postadressenservice"
                - name: ALARMENSERVICE_URL
                  value: "http://hhb-alarmenservice"
                - name: SIGNALENSERVICE_URL
                  value: "http://hhb-signalenservice"
              command:
                - flask
                - alarms
                - evaluate
