apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-backend
  labels:
    name: hhb-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-backend
  template:
    metadata:
      labels:
        name: hhb-backend
    spec:
      containers:
        - name: hhb-backend
          image: backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/health
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: APP_SETTINGS
              value: "hhb_backend.config.ProductionConfig"
            - name: AUTH_AUDIENCE
              value: "change this in a patch"
            - name: JWT_SECRET
              value: "change this in a patch"
            - name: PREFIX
              value: "/api"
            - name: HHB_SERVICE_URL
              value: "http://hhb-huishoudboekjeservice"
            - name: ORGANISATIE_SERVICE_URL
              value: "http://hhb-organisatieservice"
            - name: TRANSACTIE_SERVICE_URL
              value: "http://hhb-banktransactieservice"
            - name: GROOTBOEK_SERVICE_URL
              value: "http://hhb-grootboekservice"
            - name: LOG_SERVICE_URL
              value: "http://hhb-logservice"
            - name: POSTADRESSENSERVICE_URL
              value: "http://hhb-postadressenservice"
            - name: ALARMENSERVICE_URL
              value: "http://hhb-alarmenservice"
            - name: SIGNALENSERVICE_URL
              value: "http://hhb-signalenservice"
