apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-backend
  labels:
    name: hhb-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-backend
  template:
    metadata:
      labels:
        name: hhb-backend
    spec:
      containers:
        - name: hhb-backend
          image: backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/health
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: authservice-config
                  key: JWT_AUDIENCE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: authservice-config
                  key: JWT_SECRET
            - name: JWT_ALGORITHMS
              valueFrom:
                secretKeyRef:
                  name: authservice-config
                  key: JWT_ALGORITHMS
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: authservice-config
                  key: JWT_ISSUER
            - name: PREFIX
              value: "/api"
            - name: HHB_SERVICE_URL
              value: "http://hhb-huishoudboekjeservice"
            - name: ORGANISATIE_SERVICE_URL
              value: "http://hhb-organisatieservice"
            - name: TRANSACTIE_SERVICE_URL
              value: "http://hhb-banktransactieservice"
            - name: GROOTBOEK_SERVICE_URL
              value: "http://hhb-grootboekservice"
            - name: LOG_SERVICE_URL
              value: "http://hhb-logservice"
            - name: POSTADRESSENSERVICE_URL
              value: "http://hhb-postadressenservice"
            - name: ALARMENSERVICE_URL
              value: "http://hhb-alarmenservice"
            - name: SIGNALENSERVICE_URL
              value: "http://hhb-signalenservice"
            - name: RAPPORTAGE_SERVICE_URL
              value: "http://hhb-rapportageservice"
            - name: USE_GRAPHIQL
              value: "0"
            - name: LOG_LEVEL
              value: INFO
            - name: STATSD_HOST
              value: "hhb-statsd-exporter:9125"
            - name: RABBITMQ_HOST
              value: hhb-rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASS
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_PASS
