---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-backend
  labels:
    name: hhb-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-backend
  template:
    metadata:
      labels:
        name: hhb-backend
    spec:
      containers:
        - name: hhb-backend
          image: backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /api/health
              port: http
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: APP_SETTINGS
              value: "hhb_backend.config.ProductionConfig"
            - name: AUTH_AUDIENCE
              value: "must be changed with env_patch.yaml"
            - name: AUTH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hhb-client-secrets
                  key: SECRET_KEY
            - name: OIDC_CLIENT_SECRETS
              value: /opt/etc/oidc/client_secrets.json
            - name: OIDC_CLOCK_SKEW
              value: "600"
            - name: PREFIX
              value: "/api"
            - name: HHB_SERVICE_URL
              value: "http://hhb-huishoudboekjeservice"
            - name: ORGANISATIE_SERVICE_URL
              value: "http://hhb-organisatieservice"
            - name: TRANSACTIE_SERVICE_URL
              value: "http://hhb-banktransactieservice"
            - name: GROOTBOEK_SERVICE_URL
              value: "http://hhb-grootboekservice"
            - name: LOG_SERVICE_URL
              value: "http://hhb-logservice"
            - name: POSTADRESSENSERVICE_URL
              value: "http://hhb-postadressenservice"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hhb-client-secrets
                  key: SECRET_KEY
          volumeMounts:
            - name: oidc-volume
              mountPath: /opt/etc/oidc
      volumes:
        - name: oidc-volume
          secret:
            secretName: hhb-client-secrets
            items:
              - key: client_secrets.json
                path: client_secrets.json
