apiVersion: v1
kind: Secret
metadata:
  name: hhb-client-secrets
  namespace: ${NAMESPACE}
  labels:
    name: hhb-client-secrets
stringData:
  SECRET_KEY: ${HHB_SECRET}
  client_secrets.json: |
    {
      "web": {
        "mark": true,
        "auth_uri": "http://dex.${HHB_HOST}/auth",
        "client_id": "huishoudboekje",
        "client_secret": "${HHB_SECRET}",
        "issuer": "http://dex.${HHB_HOST}",
        "redirect_uris":
          [
              "http://${HHB_HOST}/api/oidc_callback"
          ],
        "token_uri": "http://dex.${HHB_HOST}/token",
        "token_introspection_uri": "http://dex.${HHB_HOST}/tokeninfo",
        "userinfo_uri": "http://dex.${HHB_HOST}/userinfo"
      }
    }
