{{- $root := . -}}
{{- range $index, $job := .Values.jobs }}
  {{- with $root }}
  {{- if eq .Values.jobType $job.type }}
  {{- $jobName := printf "%s-%s-%s" (include "sample-data.fullname" .) $job.serviceName $job.type}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
    {{- include "sample-data.labels" . | nindent 4 }}
spec:
  activeDeadlineSeconds: {{ .Values.containers.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.containers.ttlSecondsAfterFinished }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sample-data.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sample-data.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $jobName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s:%s" (.Values.image.repository) (include "sample-data.imageTag" .) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" (.Values.database.serviceName) $job.serviceName | quote }}
                  key: database
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" (.Values.database.serviceName) $job.serviceName | quote }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-%s" (.Values.database.serviceName) $job.serviceName | quote }}
                  key: password
            - name: DATABASE_URL
              value: "postgresql://$(PGUSER):$(PGPASSWORD)@{{ .Values.database.releaseName }}-postgresql/$(PGDATABASE)"
            - name: DATABASE_NAME
              value: "$(PGDATABASE)"
            {{- with $job.countTable }}
            - name: DATABASE_COUNT_TABLE
              value: {{ . }}
            {{- end }}
          command:
            {{- toYaml $job.command | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}
