apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-database
  labels:
    name: hhb-database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-database
  template:
    metadata:
      labels:
        name: hhb-database
    spec:
      initContainers:
        - name: init-chown-bitnami-postgresql
          image: busybox
          volumeMounts:
            - name: hhb-database-volume
              mountPath: /bitnami/postgresql
          command: ["chown"]
          args: ["-R", "1001:1001" , "/bitnami/postgresql"]
      containers:
        - name: hhb-database
          image: bitnami/postgresql:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 256Mi
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: hhb-database-volume
      volumes:
        - name: hhb-database-volume
          persistentVolumeClaim:
            claimName: hhb-database-pvc
