apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-database
  namespace: ${NAMESPACE}
  labels:
    name: hhb-database
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-database
  template:
    metadata:
      labels:
        name: hhb-database
    spec:
      containers:
        - name: hhb-database
          image: postgres:13-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: hhb-database-volume
      volumes:
        - name: hhb-database-volume
          persistentVolumeClaim:
            claimName: hhb-database-volumeclaim