---
apiVersion: v1
kind: Service
metadata:
  name: hhb-statsd-exporter
  labels:
    name: hhb-statsd-exporter
spec:
  type: ClusterIP
  selector:
    name: hhb-statsd-exporter
  ports:
    - protocol: TCP
      port: 9102
      targetPort: 9102
