---
apiVersion: v1
kind: Service
metadata:
  name: hhb-statsd-exporter
  labels:
    name: hhb-statsd-exporter
spec:
  type: ClusterIP
  selector:
    name: hhb-statsd-exporter
  ports:
    - name: metrics
      containerPort: 9102
      protocol: TCP
      targetPort: metrics
    - name: statsd
      containerPort: 9125
      protocol: UDP
      targetPort: statsd
