---
apiVersion: v1
kind: Service
metadata:
  name: hhb-statsd-exporter
  labels:
    name: hhb-statsd-exporter
spec:
  type: ClusterIP
  selector:
    name: hhb-statsd-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9102
      targetPort: metrics
    - name: statsd
      protocol: UDP
      port: 9125
      targetPort: statsd
