apiVersion: v1
kind: Service
metadata:
  name: hhb-redis
  labels:
    name: hhb-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    name: hhb-redis
