apiVersion: v1
kind: ConfigMap
metadata:
  name: authservice-config
data:
  OIDC_ISSUER_URL: "must be changed with env_patch.yaml"
  OIDC_CLIENT_ID: "must be changed with env_patch.yaml"
  OIDC_CLIENT_SECRET: "must be changed with env_patch.yaml"
  OIDC_BASE_URL: "must be changed with env_patch.yaml"
  JWT_SECRET: "must be changed with env_patch.yaml"
  JWT_ISSUER: "must be changed with env_patch.yaml"
  JWT_AUDIENCE: "must be changed with env_patch.yaml"
  JWT_EXPIRES_IN: "must be changed with env_patch.yaml"
