apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-authservice
  labels:
    name: hhb-authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-authservice
  template:
    metadata:
      labels:
        name: hhb-authservice
    spec:
      containers:
        - name: hhb-authservice
          image: authservice
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: "300m"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: authservice-config
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-url
                  key: REDIS_URL
#          env:
#            - name: OIDC_ISSUER_URL
#              value: "comes from authservice-config configMap"
#            - name: OIDC_CLIENT_ID
#              value: "comes from authservice-config configMap"
#            - name: OIDC_CLIENT_SECRET
#              value: "comes from authservice-config configMap"
#            - name: OIDC_BASE_URL
#              value: "comes from authservice-config configMap"
#            - name: JWT_ISSUER
#              value: "comes from authservice-config configMap"
#            - name: JWT_AUDIENCE
#              value: "comes from authservice-config configMap"
#            - name: JWT_SECRET
#              value: "comes from authservice-config configMap"
#            - name: JWT_EXPIRES_IN
#              value: "comes from authservice-config configMap"
