// @no-log
GET http://localhost:8080/v1/addresses/2fc9baf4-f85b-4643-b525-bb901ab825dc
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/addresses/deze-bestaat-zeker-niet
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/addresses
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/addresses?filter_ids=2fc9baf4-f85b-4643-b525-bb901ab825dc,test
Accept: application/json
Content-Type: application/json

###

// @no-log
POST http://localhost:8080/v1/addresses
Accept: application/json
Content-Type: application/json

{
  "street": "Teststraat",
  "houseNumber": "123A",
  "postalCode": "9999ZZ",
  "locality": "Sloothuizen"
}

###

// @no-log
PUT http://localhost:8080/v1/addresses/e7fb948f-b589-4dfe-9c05-d51f11a88e64
Accept: application/json
Content-Type: application/json

{
  "street": "Kerkstraat",
  "houseNumber": "321B",
  "postalCode": "1234AB",
  "locality": "Sloothuizerveen"
}

###

// @no-log
PUT http://localhost:8080/v1/addresses/deze-bestaat-niet
Accept: application/json
Content-Type: application/json

{
  "street": "Kerkstraat",
  "houseNumber": "321B",
  "postalCode": "1234AB",
  "locality": "Sloothuizerveen"
}

###

// @no-log
DELETE http://localhost:8080/v1/addresses/deze-bestaat-niet
Accept: application/json
Content-Type: application/json

###

// @no-log
DELETE http://localhost:8080/v1/addresses/e7fb948f-b589-4dfe-9c05-d51f11a88e64
Accept: application/json
Content-Type: application/json

###
