// @no-log
GET http://localhost:8080/v1/addresses/e7fb948f-b589-4dfe-9c05-d51f11a88e64
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/addresses/deze-bestaat-zeker-niet
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/addresses
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/addresses?filter_ids=119be6cf-d7db-4d06-9604-175226fe2b85,567634fd-bb4e-4c97-a0ec-26f072d711d9,dezeisnietgevonden
Accept: application/json
Content-Type: application/json

###

// @no-log
POST http://localhost:8080/v1/addresses
Accept: application/json
Content-Type: application/json

{
"street": "Teststraat",
"houseNumber": "123A",
"postalCode": "9999ZZ",
"locality": "Sloothuizerveenhuizen"
}

###

// @no-log
PUT http://localhost:8080/v1/addresses/e7fb948f-b589-4dfe-9c05-d51f11a88e64
Accept: application/json
Content-Type: application/json

{
"street": "Teststraat 3",
"houseNumber": "321B",
"postalCode": "1234AB",
"locality": "Sloothuizerveen"
}

###

// @no-log
PUT http://localhost:8080/v1/addresses/deze-bestaat-niet
Accept: application/json
Content-Type: application/json

{
"street": "Teststraat 2",
"houseNumber": "321B",
"postalCode": "1234AB",
"locality": "Sloothuizerveen"
}

###

// @no-log
DELETE http://localhost:8080/v1/addresses/deze-bestaat-niet
Accept: application/json
Content-Type: application/json

###

// @no-log
DELETE http://localhost:8080/v1/addresses/e7fb948f-b589-4dfe-9c05-d51f11a88e64
Accept: application/json
Content-Type: application/json

###
