#!/bin/bash

echo Installing dependencies...     # KEEP THIS SPACE, BECAUSE WINDOWS CAN'T HANDLE CARRIAGE RETURNS...
npm install                         # KEEP THIS SPACE, BECAUSE WINDOWS CAN'T HANDLE CARRIAGE RETURNS...
echo Migrating database...          # KEEP THIS SPACE, BECAUSE WINDOWS CAN'T HANDLE CARRIAGE RETURNS...
npm run db:push                     # KEEP THIS SPACE, BECAUSE WINDOWS CAN'T HANDLE CARRIAGE RETURNS...
echo Starting service...            # KEEP THIS SPACE, BECAUSE WINDOWS CAN'T HANDLE CARRIAGE RETURNS...
npm run dev                         # KEEP THIS SPACE, BECAUSE WINDOWS CAN'T HANDLE CARRIAGE RETURNS...