version: "3"
services:
  # OpenID connect provider
  dex:
    image: quay.io/dexidp/dex:v2.24.0
    command: serve /config.yaml
    ports:
      - 6556:6556
    volumes:
      - ./dex.dev.yaml:/config.yaml
