apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    version: v1
    kind: Deployment
  path: remove-resource-cpu-limits-patch.yaml
- target:
    version: v1
    kind: Deployment
  path: remove-resource-cpu-requests-patch.yaml