apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
  - name: authservice-config
    literals:
      - OIDC_ISSUER_URL=${OIDC_ISSUER_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_BASE_URL=${OIDC_BASE_URL}
      - OIDC_SCOPES=${OIDC_SCOPES}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHMS=${JWT_ALGORITHMS}
  - name: unleash-config
    literals:
      - UNLEASH_OTAP=${UNLEASH_OTAP}
  - name: postgres-config
    literals:
      - POSTGRESQL_HOSTNAME=${POSTGRESQL_HOSTNAME}
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_DATABASE_NAME_BKTSVC=${POSTGRESQL_DATABASE_NAME_BKTSVC}
      - POSTGRESQL_DATABASE_NAME_GRBSVC=${POSTGRESQL_DATABASE_NAME_GRBSVC}
      - POSTGRESQL_DATABASE_NAME_HHBSVC=${POSTGRESQL_DATABASE_NAME_HHBSVC}
      - POSTGRESQL_DATABASE_NAME_LOGSVC=${POSTGRESQL_DATABASE_NAME_LOGSVC}
      - POSTGRESQL_DATABASE_NAME_ORGSVC=${POSTGRESQL_DATABASE_NAME_ORGSVC}
      - POSTGRESQL_DATABASE_NAME_PADSVC=${POSTGRESQL_DATABASE_NAME_PADSVC}
      - POSTGRESQL_DATABASE_NAME_ALMSVC=${POSTGRESQL_DATABASE_NAME_ALMSVC}
      - POSTGRESQL_DATABASE_NAME_SIGSVC=${POSTGRESQL_DATABASE_NAME_SIGSVC}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_USERNAME_BKTSVC=${POSTGRESQL_USERNAME_BKTSVC}
      - POSTGRESQL_USERNAME_GRBSVC=${POSTGRESQL_USERNAME_GRBSVC}
      - POSTGRESQL_USERNAME_HHBSVC=${POSTGRESQL_USERNAME_HHBSVC}
      - POSTGRESQL_USERNAME_LOGSVC=${POSTGRESQL_USERNAME_LOGSVC}
      - POSTGRESQL_USERNAME_ORGSVC=${POSTGRESQL_USERNAME_ORGSVC}
      - POSTGRESQL_USERNAME_PADSVC=${POSTGRESQL_USERNAME_PADSVC}
      - POSTGRESQL_USERNAME_ALMSVC=${POSTGRESQL_USERNAME_ALMSVC}
      - POSTGRESQL_USERNAME_SIGSVC=${POSTGRESQL_USERNAME_SIGSVC}
secretGenerator:
  - name: redis-config-file
    files:
      - redis.conf
  - name: redis-url
    literals:
      - REDIS_URL=redis://authservice:${REDIS_AUTH_PASSWORD}@hhb-redis:6379
  - name: hhb-database-secrets
    literals:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_PASSWORD_BKTSVC=${POSTGRESQL_PASSWORD_BKTSVC}
      - POSTGRESQL_PASSWORD_GRBSVC=${POSTGRESQL_PASSWORD_GRBSVC}
      - POSTGRESQL_PASSWORD_HHBSVC=${POSTGRESQL_PASSWORD_HHBSVC}
      - POSTGRESQL_PASSWORD_LOGSVC=${POSTGRESQL_PASSWORD_LOGSVC}
      - POSTGRESQL_PASSWORD_ORGSVC=${POSTGRESQL_PASSWORD_ORGSVC}
      - POSTGRESQL_PASSWORD_PADSVC=${POSTGRESQL_PASSWORD_PADSVC}
      - POSTGRESQL_PASSWORD_ALMSVC=${POSTGRESQL_PASSWORD_ALMSVC}
      - POSTGRESQL_PASSWORD_SIGSVC=${POSTGRESQL_PASSWORD_SIGSVC}
      - HUISHOUDBOEKJESERVICE_DATABASE_URL="postgresql://$POSTGRESQL_USERNAME_HHBSVC:$POSTGRESQL_PASSWORD_HHBSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_HHBSVC"
      - GROOTBOEKSERVICE_DATABASE_URL="postgresql://$POSTGRESQL_USERNAME_GRBSVC:$POSTGRESQL_PASSWORD_GRBSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_GRBSVC"
      - LOGSERVICE_DATABASE_URL="postgresql://$POSTGRESQL_USERNAME_LOGSVC:$POSTGRESQL_PASSWORD_LOGSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_LOGSVC"
      - ORGANISATIESERVICE_DATABASE_URL="postgresql://$POSTGRESQL_USERNAME_ORGSVC:$POSTGRESQL_PASSWORD_ORGSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_ORGSVC"
      - TRANSACTIESERVICE_DATABASE_URL="postgresql://$POSTGRESQL_USERNAME_BKTSVC:$POSTGRESQL_PASSWORD_BKTSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_BKTSVC"
      - POSTADRESSENSERVICE_DATABASE_URL="postgresql://$POSTGRESQL_USERNAME_PADSVC:$POSTGRESQL_PASSWORD_PADSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_PADSVC"
      - ALARMENSERVICE_DATABASE_URL="postgresql://$POSTGRESQL_USERNAME_ALMSVC:$POSTGRESQL_PASSWORD_ALMSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_ALMSVC"
      - SIGNALENSERVICE_DATABASE_URL="postgresql://$POSTGRESQL_USERNAME_SIGSVC:$POSTGRESQL_PASSWORD_SIGSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_SIGSVC"
