apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
  path: ./host-name/ingress-host-patch.yaml
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
  path: ./class-name/ingress-className-patch.yaml