apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'hhb-statsd-exporter'
        static_configs:
          - targets: ['hhb-statsd-exporter:9102']
      - job_name: 'hhb-rabbitmq'
        static_configs:
          - targets: ['hhb-rabbitmq:15692']
      - job_name: 'hhb-logservice'
        static_configs:
          - targets: ['hhb-logservice:9000']