---
apiVersion: v1
kind: Service
metadata:
  name: hhb-prometheus
  labels:
    name: hhb-prometheus
spec:
  type: ClusterIP
  selector:
    name: hhb-prometheus
  ports:
    - name: prometheus
      protocol: TCP
      port: 80
      targetPort: prometheus
