"""Initial database creation

Revision ID: 79e487a2dcc3
Revises: 
Create Date: 2020-10-01 13:19:29.163853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e487a2dcc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gebruikers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefoonnummer', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('geboortedatum', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('burgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gebruiker_id', sa.Integer(), nullable=True),
    sa.Column('voornamen', sa.String(), nullable=True),
    sa.Column('voorletters', sa.String(), nullable=True),
    sa.Column('voorvoegsel', sa.String(), nullable=True),
    sa.Column('geslachtsnaam', sa.String(), nullable=True),
    sa.Column('straatnaam', sa.String(), nullable=True),
    sa.Column('huisnummer', sa.Integer(), nullable=True),
    sa.Column('huisletter', sa.String(), nullable=True),
    sa.Column('huistoevoeging', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('woonplaatsnaam', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gebruiker_id'], ['gebruikers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burgers')
    op.drop_table('gebruikers')
    # ### end Alembic commands ###
