apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    version: v1
    kind: Deployment
  path: node-selector-patch.yaml
- target:
    version: v1
    kind: StatefulSet
  path: node-selector-patch.yaml
- target:
    version: v1
    kind: CronJob
  path: node-selector-patch-job.yaml