apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-database-mesh
  labels:
    name: hhb-database-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-database-mesh
  template:
    metadata:
      labels:
        name: hhb-database-mesh
    spec:
      containers:
        - name: hhb-database-mesh
          image: databasemesh
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 1000Mi
            requests:
              cpu: 150m
              memory: 512Mi
          env:
            - name: DB_HOST
              value: hhb-database

