apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-backendburgers-ingress
  labels:
    name: hhb-backendburgers-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - ${APP_HOST}
      secretName: medewerker-frontend-ingress-tls
  rules:
    - host: ${APP_HOST}
      http:
        paths:
          - path: /api/burgers
            pathType: Prefix
            backend:
              service:
                name: hhb-backendburgers
                port:
                  number: 80
