sources:
  - name: huishoudboekjeDatabase
    handler:
      postgraphile:
        connectionString: postgres://{env.DB_USER}:{env.DB_PASSWORD}@{env.DB_HOST}:{env.DB_PORT}/huishoudboekjeservice
  - name: alarmDatabase
    handler:
      postgraphile:
        connectionString: postgres://{env.DB_USER}:{env.DB_PASSWORD}@{env.DB_HOST}:{env.DB_PORT}/alarmenservice
additionalTypeDefs: |
  extend type Mutation {
    truncateTable(databaseName: String!, tableName: String!): Boolean!
  }
additionalResolvers:
  - './resolvers'
serve:
  hostname: 0.0.0.0
