---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-frontend
  labels:
    name: hhb-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-frontend
  template:
    metadata:
      labels:
        name: hhb-frontend
    spec:
      containers:
        - name: hhb-frontend
          image: frontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 12Mi
          volumeMounts:
            - name: theme-volume
              mountPath: /opt/bitnami/apps/html/theme
      volumes:
        - name: theme-volume
          configMap:
            name: hhb-theme
