apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-frontend
  namespace: ${NAMESPACE}
  labels:
    name: hhb-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - ${HHB_HOST}
      secretName: hhb-frontend-ingress-tls
  rules:
    - host: ${HHB_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hhb-frontend
                port:
                  number: 80