---
apiVersion: v1
kind: Service
metadata:
  name: hhb-logservice
  labels:
    name: hhb-logservice
spec:
  type: ClusterIP
  selector:
    name: hhb-logservice
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: grpc
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: metrics
