"""added rekening table

Revision ID: ecbc3b773853
Revises: f53e311ed706
Create Date: 2020-10-21 14:40:17.785858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbc3b773853'
down_revision = 'f53e311ed706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rekening',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(), nullable=False),
    sa.Column('rekeninghouder', sa.String(), nullable=False),
    sa.Column('gebruiker_id', sa.Integer(), nullable=True),
    sa.Column('organisatie_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('NOT(organisatie_id IS NULL AND gebruiker_id IS NULL)'),
    sa.ForeignKeyConstraint(['gebruiker_id'], ['gebruikers.id'], ),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rekening')
    # ### end Alembic commands ###
