// @no-log
GET http://localhost:8080/v1/alarms/71d65065-2eb9-4f44-8f16-44d1e5a4d6f8
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/alarms/deze-bestaat-zeker-niet
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/alarms
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/alarms?filter_ids=71d65065-2eb9-4f44-8f16-44d1e5a4d6f8,567634fd-bb4e-4c97-a0ec-26f072d711d9,dezeisnietgevonden
Accept: application/json
Content-Type: application/json

###

// @no-log
GET http://localhost:8080/v1/alarms?filter_active=true
Accept: application/json
Content-Type: application/json

###

// @no-log
POST http://localhost:8080/v1/alarms
Accept: application/json
Content-Type: application/json

{
  "byDay": ["Monday", "Tuesday"],
  "byMonth": [1, 2, 3, 4, 11, 12],
  "byMonthDay": [3],
  "afspraakId": 1,
  "isActive": true,
  "startDate": "2021-12-18",
  "endDate": "2022-12-17",
  "datumMargin": 3,
  "bedrag": 1200.12,
  "bedragMargin": 75.25
}

###

// @no-log
PUT http://localhost:8080/v1/alarms/71d65065-2eb9-4f44-8f16-44d1e5a4d6f8
Accept: application/json
Content-Type: application/json

{
  "byDay": ["Monday", "Tuesday"],
  "byMonth": [1, 2, 3, 4, 11, 12],
  "byMonthDay": [3],
  "afspraakId": 1,
  "isActive": true,
  "startDate": "2021-12-18",
  "endDate": "2022-12-17",
  "datumMargin": 3,
  "bedrag": 1200.12,
  "bedragMargin": 75.25
}

###

// @no-log
PUT http://localhost:8080/v1/alarms/deze-bestaat-niet
Accept: application/json
Content-Type: application/json

{
  "byDay": ["Monday", "Tuesday"],
  "byMonth": [1, 2, 3, 4, 11, 12],
  "byMonthDay": [3],
  "afspraakId": 1,
  "isActive": true,
  "startDate": "2021-12-18",
  "endDate": "2022-12-17",
  "datumMargin": 3,
  "bedrag": 1200.12,
  "bedragMargin": 75.25
}

###

// @no-log
DELETE http://localhost:8080/v1/alarms/deze-bestaat-niet
Accept: application/json
Content-Type: application/json

###

// @no-log
DELETE http://localhost:8080/v1/alarms/71d65065-2eb9-4f44-8f16-44d1e5a4d6f8
Accept: application/json
Content-Type: application/json

###
