apiVersion: v1
kind: Service
metadata:
  name: hhb-rabbitmq
  labels:
    name: hhb-rabbitmq
spec:
  type: ClusterIP
  selector:
    name: hhb-rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    - name: management
      protocol: TCP
      port: 15672
      targetPort: management
    - name: prometheus
      protocol: TCP
      port: 15692
      targetPort: prometheus
