apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hhb-rabbitmq
  labels:
    name: hhb-rabbitmq
spec:
  replicas: 1
  serviceName: hhb-rabbitmq
  selector:
    matchLabels:
      name: hhb-rabbitmq
  template:
    metadata:
      labels:
        name: hhb-rabbitmq
    spec:
      containers:
        - name: hhb-rabbitmq
          image: rabbitmq:3.12-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
            - name: prometheus
              containerPort: 15692
              protocol: TCP
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          # livenessProbe:
          #     exec:
          #       command:
          #       - rabbitmq-diagnostics
          #       - status
          #     initialDelaySeconds: 60
          #     periodSeconds: 60
          #     timeoutSeconds: 15
          # readinessProbe:
          #     exec:
          #       command:
          #       - rabbitmq-diagnostics
          #       - ping
          #     initialDelaySeconds: 20
          #     periodSeconds: 60
          #     timeoutSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi
          volumeMounts:
            - name: rabbitmq-plugins
              mountPath: /etc/rabbitmq
            - name: hhb-rabbitmq-data-pvc
              mountPath: /var/lib/rabbitmq/mnesia
      volumes:
        - name: rabbitmq-plugins
          configMap:
            name: rabbitmq-plugins
  volumeClaimTemplates:
    - metadata:
        name: hhb-rabbitmq-data-pvc
      spec:
        storageClassName: "default"
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512Mi