apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hhb-rabbitmq-data
  labels:
    name: hhb-rabbitmq-data
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
