apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
components:
  - ../components/configmaps
  - ../components/set-images
  - ../components/patches/letsencrypt
  - ../components/patches/ingress
  - ../components/patches/review-agent-pool
  # - resources
patches:
- target:
    version: v1
    kind: Deployment
  path: patches/remove-resource-limits-patch.yaml
- target:
    version: v1
    kind: Deployment
    name: hhb-backend
  path: patches/allow-introspection-patch.yaml
- target:
    version: v1
    kind: Deployment
    name: hhb-huishoudboekjeservice
  path: patches/seed-test-data-patch.yaml
- target:
    version: v1
    kind: Deployment
    name: hhb-organisatieservice
  path: patches/seed-test-data-patch.yaml
- target:
    version: v1
    kind: Deployment
    name: hhb-postadressenservice
  path: patches/seed-test-data-patch.yaml

