CREATE USER hhb WITH PASSWORD 'hhb';
ALTER USER hhb WITH SUPERUSER;
CREATE DATABASE huishoudboekjeservice;
CREATE DATABASE organisatieservice;
CREATE DATABASE banktransactieservice;
CREATE DATABASE grootboekservice;
CREATE DATABASE logservice;
CREATE DATABASE postadressenservice;
CREATE DATABASE alarmenservice;
CREATE DATABASE fileservice;