"""added filename column for csm

Revision ID: 5f85b2dc39e6
Revises: b32deba9b73f
Create Date: 2021-03-03 15:29:28.927970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f85b2dc39e6'
down_revision = 'b32deba9b73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_statement_messages', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_statement_messages', 'filename')
    # ### end Alembic commands ###
