"""add is_geboekt column

Revision ID: b32deba9b73f
Revises: f9646c4e558e
Create Date: 2021-02-14 15:26:31.069049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32deba9b73f'
down_revision = 'f9646c4e558e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('is_geboekt', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_bank_transactions_is_geboekt'), 'bank_transactions', ['is_geboekt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_is_geboekt'), table_name='bank_transactions')
    op.drop_column('bank_transactions', 'is_geboekt')
    # ### end Alembic commands ###
