"""Added bank transaction table

Revision ID: b7000394a36b
Revises: 52dd4e1665ec
Create Date: 2020-11-10 16:52:35.489095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7000394a36b'
down_revision = '52dd4e1665ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_statement_message_id', sa.Integer(), nullable=False),
    sa.Column('statement_line', sa.String(), nullable=True),
    sa.Column('information_to_account_owner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_statement_message_id'], ['customer_statement_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
