"""Added cascade delete on bank_transactions

Revision ID: e71df17362cf
Revises: b7000394a36b
Create Date: 2020-11-18 11:49:36.325603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71df17362cf'
down_revision = 'b7000394a36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_transactions_customer_statement_message_id_fkey', 'bank_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'bank_transactions', 'customer_statement_messages', ['customer_statement_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.create_foreign_key('bank_transactions_customer_statement_message_id_fkey', 'bank_transactions', 'customer_statement_messages', ['customer_statement_message_id'], ['id'])
    # ### end Alembic commands ###
