"""added extra bank transactions columns

Revision ID: f9646c4e558e
Revises: b7000394a36b
Create Date: 2020-11-17 16:38:02.727141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9646c4e558e'
down_revision = 'b7000394a36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('bedrag', sa.Integer(), nullable=True))
    op.add_column('bank_transactions', sa.Column('is_credit', sa.Boolean(), nullable=True))
    op.add_column('bank_transactions', sa.Column('tegen_rekening', sa.String(), nullable=True))
    op.add_column('bank_transactions', sa.Column('transactie_datum', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank_transactions', 'transactie_datum')
    op.drop_column('bank_transactions', 'tegen_rekening')
    op.drop_column('bank_transactions', 'is_credit')
    op.drop_column('bank_transactions', 'bedrag')
    # ### end Alembic commands ###
