apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-signalenservice
  labels:
    name: hhb-signalenservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-signalenservice
  template:
    metadata:
      labels:
        name: hhb-signalenservice
    spec:
      initContainers:
        - name: init1-wait-for-db
          image: busybox
          command:
            [
                "sh",
                "-c",
                "while true; do sleep 1; echo Waiting for database...; if nc -z hhb-database 5432; then echo Database is up!; exit 0; fi; done; echo Aint gonna wait for the database forever...; exit 1",
            ]
        - name: init2-prepare-db
          image: bitnami/postgresql:13
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_PASSWORD_SIGSVC
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD_SIGSVC
          command: [ "/bin/sh" ]
          args:
            - -c
            - >-
              export PGPASSWORD=$POSTGRESQL_PASSWORD &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "CREATE USER sigsvc WITH PASSWORD '$POSTGRESQL_PASSWORD_SIGSVC'" || true &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "CREATE DATABASE signalenservice" || true &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "GRANT ALL PRIVILEGES ON DATABASE signalenservice TO sigsvc" || true &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "ALTER USER sigsvc WITH PASSWORD '$POSTGRESQL_PASSWORD_SIGSVC'" || true;
        - name: init3-migrate-db
          image: signalenservice
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: HHB_SECRET
              valueFrom:
                secretKeyRef:
                  name: hhb-client-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: SIGNALENSERVICE_DATABASE_URL
          command: [ "npm" ]
          args: [ "run", "db:push" ]
          volumeMounts:
            - mountPath: /app/node_modules/.prisma
              name: prisma-signalenservice-init-3
            - mountPath: /app/node_modules/prisma
              name: app-node-modules-prisma-signalenservice-init-3
            - mountPath: /.npm
              name: npm-signalenservice-init-3
      containers:
        - name: hhb-signalenservice
          image: signalenservice
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: SIGNALENSERVICE_DATABASE_URL
          volumeMounts:
            - mountPath: /app/node_modules/.prisma
              name: prisma-signalenservice
            - mountPath: /.npm
              name: npm-signalenservice
            - mountPath: /app/node_modules/prisma
              name: app-node-modules-prisma-signalenservice
      volumes:
        - emptyDir: {}
          name: prisma-signalenservice-init-3
        - emptyDir: {}
          name: prisma-signalenservice
        - emptyDir: {}
          name: app-node-modules-prisma-signalenservice-init-3
        - emptyDir: {}
          name: app-node-modules-prisma-signalenservice
        - emptyDir: {}
          name: npm-signalenservice-init-3
        - emptyDir: {}
          name: npm-signalenservice