---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-postadressenservice
  labels:
    name: hhb-postadressenservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-postadressenservice
  template:
    metadata:
      labels:
        name: hhb-postadressenservice
    spec:
      initContainers:
        - name: init1-wait-for-db
          image: busybox
          envFrom:
            - configMapRef:
                name: postgres-config
          command:
            [
              "sh",
              "-c",
              "while true; do sleep 1; echo Waiting for database...; if nc -z $POSTGRESQL_HOSTNAME $POSTGRESQL_PORT; then echo Database is up!; exit 0; fi; done; echo Aint gonna wait for the database forever...; exit 1",
            ]
        - name: init2-prepare-db
          image: bitnami/postgresql:13
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_PASSWORD_PADSVC
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD_PADSVC
          command: [ "/bin/sh" ]
          args:
            - -c
            - >-
              export PGPASSWORD=$POSTGRESQL_PASSWORD &&
              export PGPORT=$POSTGRESQL_PORT &&
              psql -h $POSTGRESQL_HOSTNAME -U $POSTGRESQL_USERNAME -c "CREATE USER $POSTGRESQL_USERNAME_PADSVC WITH PASSWORD '$POSTGRESQL_PASSWORD_PADSVC'" || true &&
              psql -h $POSTGRESQL_HOSTNAME -U $POSTGRESQL_USERNAME -c "CREATE DATABASE $POSTGRESQL_DATABASE_NAME_PADSVC" || true &&
              psql -h $POSTGRESQL_HOSTNAME -U $POSTGRESQL_USERNAME -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRESQL_DATABASE_NAME_PADSVC TO $POSTGRESQL_USERNAME_PADSVC" || true &&
              psql -h $POSTGRESQL_HOSTNAME -U $POSTGRESQL_USERNAME -c "ALTER USER $POSTGRESQL_USERNAME_PADSVC WITH PASSWORD '$POSTGRESQL_PASSWORD_PADSVC'" || true;
        - name: init3-migrate-db
          image: postadressenservice
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTADRESSENSERVICE_DATABASE_URL
          command: [ "npm" ]
          args: [ "run", "db:deploy" ]
      containers:
        - name: hhb-postadressenservice
          image: postadressenservice
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTADRESSENSERVICE_DATABASE_URL
