configuratie:
  - id: derdengeldenrekening_rekeninghouder
    waarde: "Gemeente Sloothuizen Huishoudboekje"
  - id: derdengeldenrekening_iban
    waarde: "NL36ABNA5632579034"
  - id: derdengeldenrekening_bic
    waarde: "ABNANL2A"

rubrieken:
  # Inkomsten
  - id: 1
    naam: "Inkomsten"
    grootboekrekening_id: "WOmzNooNdo"
  - id: 2
    naam: "Toeslagen"
    grootboekrekening_id: "WOvbOrsOsuSro"
  - id: 3
    naam: "Uitkeringen"
    grootboekrekening_id: "WOvbOrsOsuSov"
  - id: 4
    naam: "Subsidies"
    grootboekrekening_id: "WOvbOrsOsuSpo"
  
  # Uitgaven
  # Gebaseerd op definitie vaste lasten van Nibud, TODO onderwijs, kinderopvang, vervoer
  - id: 6
    naam: "Huur of hypotheek"
    grootboekrekening_id: "WBedHuiBeh"
  - id: 7
    naam: "Gas en elektriciteit"
    grootboekrekening_id: "WBedHuiGweElk"
  - id: 8
    naam: "Water"
    grootboekrekening_id: "WBedHuiGweWat"
  - id: 9
    naam: "Lokale lasten"
    grootboekrekening_id: "WBedHuiMez"
  - id: 10
    naam: "Telefoon, internet en televisie"
    grootboekrekening_id: "WBedKanTef"
  - id: 11
    naam: "Verzekeringen"
    grootboekrekening_id: "WBedAssOva"
  - id: 12
    naam: "Privé-opname"
    grootboekrekening_id: "BEivKapProPok"
