dex:
  enabled: false

postgres-operator:
  configKubernetes:
    watched_namespace: ""

database:
  enabled: true

  nameOverride: "huishoudboekje"

  databases:
    - gebruikers
    - organisaties
    - afspraken
