dex:
  enabled: false

postgres-operator:
  configKubernetes:
    watched_namespace: ""

database:
  enabled: true

  nameOverride: "huishoudboekje"

  databases:
    - huishoudboekje_service
    - organisaties
    - afspraken

huishoudboekje-service:
  database:
    service: huishoudboekje-database
    name: huishoudboekjeservice
