dex:
  enabled: false
postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
    existingClaim: null
  initdbScriptsSecret: database-init-scripts
services:
  - huishoudboekje_service
  - organisatie_service
  - bank_transactie_service
  - grootboek_service
global:
  imageTag: "123"
