dex:
  enabled: false

postgresql:
  enabled: true
  persistence:
    enabled: false
    size: 1Gi
    existingClaim: null
  initdbScriptsSecret: database-init-scripts

services:
  - huishoudboekje_service
  - organisatie_service
  - bank_transactie_service
  - grootboek_service
