dex:
  enabled: false

postgres-operator:
  configKubernetes:
    watched_namespace: ""

database:
  enabled: true

  nameOverride: "huishoudboekje"

  databases:
    - huishoudboekjeservice
    - organisatieservice
    - transactieservice

huishoudboekje-service:
  database:
    service: huishoudboekje-database
    name: huishoudboekjeservice

organisatie-service:
  database:
    service: huishoudboekje-database
    name: organisatieservice

transactie-service:
  database:
    service: huishoudboekje-database
    name: transactieservice