"""Creation of organisaties table

Revision ID: 6612f2dd5c5a
Revises: 
Create Date: 2020-10-12 12:17:28.467953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6612f2dd5c5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisaties',
    sa.Column('kvk_nummer', sa.String(), nullable=False),
    sa.Column('naam', sa.String(), nullable=True),
    sa.Column('straatnaam', sa.String(), nullable=True),
    sa.Column('huisnummer', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('plaatsnaam', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('kvk_nummer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisaties')
    # ### end Alembic commands ###
