---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: hhb-database-volume
  labels:
    name: hhb-database-volume
spec:
  storageClassName: ${STORAGECLASSNAME}
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hhb-database-volumeclaim
  labels:
    name: hhb-database-volumeclaim
spec:
  storageClassName: ${STORAGECLASSNAME}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
