"""create burger table

Revision ID: 7958d56e9ac4
Revises: 
Create Date: 2020-10-13 17:52:09.471192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7958d56e9ac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornamen', sa.String(), nullable=True),
    sa.Column('voorletters', sa.String(), nullable=True),
    sa.Column('achternaam', sa.String(), nullable=True),
    sa.Column('straatnaam', sa.String(), nullable=True),
    sa.Column('huisnummer', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.Column('woonplaatsnaam', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burgers')
    # ### end Alembic commands ###