apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-alarmenservice
  labels:
    name: hhb-alarmenservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-alarmenservice
  template:
    metadata:
      labels:
        name: hhb-alarmenservice
    spec:
      initContainers:
        - name: init1-wait-for-db
          image: busybox
          command:
            [
                "sh",
                "-c",
                "while true; do sleep 1; echo Waiting for database...; if nc -z hhb-database 5432; then echo Database is up!; exit 0; fi; done; echo Aint gonna wait for the database forever...; exit 1",
            ]
        - name: init2-prepare-db
          image: bitnami/postgresql:13
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_PASSWORD_ALMSVC
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD_ALMSVC
          command: [ "/bin/sh" ]
          args:
            - -c
            - >-
              export PGPASSWORD=$POSTGRESQL_PASSWORD &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "CREATE USER almsvc WITH PASSWORD '$POSTGRESQL_PASSWORD_ALMSVC'" || true &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "CREATE DATABASE alarmenservice" || true &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "GRANT ALL PRIVILEGES ON DATABASE alarmenservice TO almsvc" || true &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "ALTER USER almsvc WITH PASSWORD '$POSTGRESQL_PASSWORD_ALMSVC'" || true;
        - name: init3-migrate-db
          image: alarmenservice
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: HHB_SECRET
              valueFrom:
                secretKeyRef:
                  name: hhb-client-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: ALARMENSERVICE_DATABASE_URL
          command: ["npm"]
          args: ["run", "db:push"]
      containers:
        - name: hhb-alarmenservice
          image: alarmenservice
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: ALARMENSERVICE_DATABASE_URL
