---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-organisatieservice
  labels:
    name: hhb-organisatieservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-organisatieservice
  template:
    metadata:
      labels:
        name: hhb-organisatieservice
    spec:
      initContainers:
        - name: init1-wait-for-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "while true; do sleep 1; echo Waiting for database...; if nc -z hhb-database 5432; then echo Database is up!; exit 0; fi; done; echo Aint gonna wait for the database forever...; exit 1",
            ]
        - name: init2-prepare-db
          image: bitnami/postgresql:13
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_PASSWORD_ORGSVC
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: POSTGRESQL_PASSWORD_ORGSVC
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              export PGPASSWORD=$POSTGRESQL_PASSWORD &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "CREATE USER orgsvc WITH PASSWORD '$POSTGRESQL_PASSWORD_ORGSVC'" || true &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "CREATE DATABASE organisatieservice" || true &&
              psql -h hhb-database -U $POSTGRESQL_USERNAME -c "GRANT ALL PRIVILEGES ON DATABASE organisatieservice TO orgsvc" || true;
        - name: init3-migrate-db
          image: organisatieservice
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: HHB_SECRET
              valueFrom:
                secretKeyRef:
                  name: hhb-client-secrets
                  key: SECRET_KEY
            - name: ORGANISATIE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: ORGANISATIE_DATABASE_URL
          command: ["python"]
          args: ["manage.py", "db", "upgrade"]
      containers:
        - name: hhb-organisatieservice
          image: organisatieservice
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          #          resources:
          #            limits:
          #              cpu: 1000m
          #              memory: 256Mi
          #            requests:
          #              cpu: 100m
          #              memory: 128Mi
          env:
            - name: HHB_SECRET
              valueFrom:
                secretKeyRef:
                  name: hhb-client-secrets
                  key: SECRET_KEY
            - name: ORGANISATIE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-database-secrets
                  key: ORGANISATIE_DATABASE_URL
