"""empty message

Revision ID: 38538e785b39
Revises: a751db4066ae
Create Date: 2021-11-01 12:39:57.491940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38538e785b39'
down_revision = 'a751db4066ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afdelingen', sa.Column('rekeningen_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('afdelingen', 'rekeningen_ids')
    # ### end Alembic commands ###
###this is a test