"""empty message

Revision ID: a751db4066ae
Revises: cb700aeb6e23
Create Date: 2021-09-16 10:37:09.679629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a751db4066ae'
down_revision = 'cb700aeb6e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postadressen')
    op.add_column('afdelingen', sa.Column('postadressen_ids', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('afdelingen', 'postadressen_ids')
    op.create_table('postadressen',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('postadres_service_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('afdeling_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['afdeling_id'], ['afdelingen.id'], name='postadressen_afdeling_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='postadressen_pkey')
    )
    # ### end Alembic commands ###
