"""empty message

Revision ID: cb700aeb6e23
Revises: 3c56ed782e5e
Create Date: 2021-09-10 09:04:36.188018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb700aeb6e23'
down_revision = '3c56ed782e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisaties', sa.Column('kvknummer', sa.String(), nullable=True))
    op.drop_column('organisaties', 'kvk_nummer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisaties', sa.Column('kvk_nummer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('organisaties', 'kvknummer')
    # ### end Alembic commands ###
