import React from 'react';
import {Box, Text} from "@chakra-ui/core";

// Todo: version should come from version.ts which is generated by package.json
const VersionTag = () => {
	return (
		<Text fontSize={"xs"} color={"gray.500"}>v0.0.0-dev</Text>
	);
};

export default VersionTag;