
import React from "react";
import {BoxProps, Stack, Text} from "@chakra-ui/core";

// Todo: version should come from version.ts which is generated by package.json
const VersionTag: React.FC<BoxProps> = (props) => {
	return (
		<Stack spacing={2} fontSize={"xs"} textAlign={"center"} {...props}>
			<Text>versie 0.0.0</Text>
			<Text>&copy; VNG Realisatie, {(new Date()).getFullYear()}</Text>
		</Stack>
	);
};

export default VersionTag;