---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: hhb-database-volume
spec:
  storageClassName: ${STORAGECLASSNAME}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hhb-database-volumeclaim
spec:
  storageClassName: ${STORAGECLASSNAME}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-dex-ingress
spec:
  tls:
    - hosts:
        - ${HHB_DEX_DNS}
  rules:
    - host: ${HHB_DEX_DNS}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hhb-dex
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-backend-ingress
spec:
  tls:
    - hosts:
        - ${HHB_FRONTEND_DNS}
  rules:
    - host: ${HHB_FRONTEND_DNS}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hhb-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-frontend-ingress
spec:
  tls:
    - hosts:
        - ${HHB_FRONTEND_DNS}
  rules:
    - host: ${HHB_FRONTEND_DNS}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hhb-frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-unleashservice
spec:
  tls:
    - hosts:
        - ${HHB_HOST}
  rules:
    - host: ${HHB_HOST}
      http:
        paths:
          - path: /api/unleash
            pathType: Prefix
            backend:
              service:
                name: hhb-unleashservice
                port:
                  number: 80
