---
apiVersion: v1
kind: Secret
metadata:
  name: hhb-client-secrets
  labels:
    name: hhb-client-secrets
stringData:
  SECRET_KEY: ${HHB_SECRET}
  client_secrets.json: |
    {
      "web": {
        "mark": true,
        "auth_uri": "${OIDC_AUTHORIZATION_ENDPOINT}",
        "client_id": "${OIDC_CLIENT_ID}",
        "client_secret": "${OIDC_CLIENT_SECRET}",
        "issuer": "${OIDC_ISSUER}",
        "redirect_uris":
          [
              "${HHB_API_ENDPOINT}/oidc_callback"
          ],
        "token_uri": "${OIDC_TOKEN_ENDPOINT}",
        "token_introspection_uri": "${OIDC_TOKENINFO_ENDPOINT}",
        "userinfo_uri": "${OIDC_USERINFO_ENDPOINT}"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: hhb-database-secrets
  labels:
    name: hhb-database-secrets
stringData:
  POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
  POSTGRESQL_PASSWORD_BKTSVC: ${POSTGRESQL_PASSWORD_BKTSVC}
  POSTGRESQL_PASSWORD_GRBSVC: ${POSTGRESQL_PASSWORD_GRBSVC}
  POSTGRESQL_PASSWORD_HHBSVC: ${POSTGRESQL_PASSWORD_HHBSVC}
  POSTGRESQL_PASSWORD_LOGSVC: ${POSTGRESQL_PASSWORD_LOGSVC}
  POSTGRESQL_PASSWORD_ORGSVC: ${POSTGRESQL_PASSWORD_ORGSVC}
  POSTGRESQL_PASSWORD_PADSVC: ${POSTGRESQL_PASSWORD_PADSVC}
  POSTGRESQL_PASSWORD_ALMSVC: ${POSTGRESQL_PASSWORD_ALMSVC}
  POSTGRESQL_PASSWORD_SIGSVC: ${POSTGRESQL_PASSWORD_SIGSVC}
  HHB_DATABASE_URL: "postgresql://hhbsvc:$POSTGRESQL_PASSWORD_HHBSVC@hhb-database/huishoudboekjeservice"
  GROOTBOEK_DATABASE_URL: "postgresql://grbsvc:$POSTGRESQL_PASSWORD_GRBSVC@hhb-database/grootboekservice"
  LOG_DATABASE_URL: "postgresql://logsvc:$POSTGRESQL_PASSWORD_LOGSVC@hhb-database/logservice"
  ORGANISATIE_DATABASE_URL: "postgresql://orgsvc:$POSTGRESQL_PASSWORD_ORGSVC@hhb-database/organisatieservice"
  TRANSACTIE_DATABASE_URL: "postgresql://bktsvc:$POSTGRESQL_PASSWORD_BKTSVC@hhb-database/banktransactieservice"
  POSTADRESSEN_DATABASE_URL: "postgresql://padsvc:$POSTGRESQL_PASSWORD_PADSVC@hhb-database/postadressenservice"
  ALARMENSERVICE_DATABASE_URL: "postgresql://almsvc:$POSTGRESQL_PASSWORD_ALMSVC@hhb-database/alarmenservice"
  SIGNALENSERVICE_DATABASE_URL: "postgresql://sigsvc:$POSTGRESQL_PASSWORD_SIGSVC@hhb-database/signalenservice"
