---
# TODO deze moet per omgeving
apiVersion: v1
kind: Secret
metadata:
  name: hhb-dex-secrets
  labels:
    name: hhb-dex-secrets
stringData:
  config.yaml: |-
    issuer: ${OIDC_ISSUER}
    storage:
      config:
        file: ':memory:'
        inCluster: true
      type: sqlite3
    logger:
      level: info
    web:
      http: 0.0.0.0:5556
    oauth2:
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    staticClients:
      - id: ${OIDC_CLIENT_ID}
        name: Huishoudboekje Schaalbaar
        redirectURIs:
          - "${HHB_API_ENDPOINT}/oidc_callback"
        secret: ${OIDC_CLIENT_SECRET}
    staticPasswords:
    - userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
      username: "koen@openweb.nl"
      email: "koen@openweb.nl"
      hash: "$2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa"
    - userID: "18a8684b-db88-4b73-90a9-3cd1661f5466"
      username: "magre"
      email: "bas.magre@topicus.nl"
      hash: "$2a$12$2hU8hddPgKYCawent4C0VeH.YDxr3KLqZYASESpxlz7AHhZJoBQWq"
    - username: henk.poortvliet@sloothuizen.nl
      email: henk.poortvliet@sloothuizen.nl
      name: Henk Poortvliet
      userID: 363283b9-07bb-4247-bfe4-977a1e221cc4
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: bauke.huijbers@vng.nl
      email: bauke.huijbers@vng.nl
      name: Bauke Huijbers
      userID: bcfe94b8-fc0e-48d8-ada7-c04f96d31e18
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: huishoudboekje010@rotterdam.nl
      email: huishoudboekje010@rotterdam.nl
      name: Gemeente Rotterdam
      userID: 397c2959-e692-42fa-ae54-fad84f4d256e
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: huishoudboekje@utrecht.nl
      email: huishoudboekje@utrecht.nl
      name: Gemeente Utrecht
      userID: 41e2bb72-f62d-44c1-ae0c-b1190892db50
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: nerds@sloothuizen.nl
      email: nerds@sloothuizen.nl
      name: Nerds Company
      userID: da072226-ce83-11eb-b8bc-0242ac130003
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: wouter.brunekreeft@topicus.nl
      email: wouter.brunekreeft@topicus.nl
      name: Wouter Brunekreeft
      userID: ptn38526-0g8d-vnk8-nsv3-sdnvj294fjvn
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    enablePasswordDB: true
    expiry:
      idTokens: 168h
---
apiVersion: v1
kind: Secret
metadata:
  name: hhb-client-secrets
  labels:
    name: hhb-client-secrets
stringData:
  SECRET_KEY: ${HHB_SECRET}
  client_secrets.json: |
    {
      "web": {
        "mark": true,
        "auth_uri": "${OIDC_AUTHORIZATION_ENDPOINT}",
        "client_id": "${OIDC_CLIENT_ID}",
        "client_secret": "${OIDC_CLIENT_SECRET}",
        "issuer": "${OIDC_ISSUER}",
        "redirect_uris":
          [
              "${HHB_API_ENDPOINT}/oidc_callback"
          ],
        "token_uri": "${OIDC_TOKEN_ENDPOINT}",
        "token_introspection_uri": "${OIDC_TOKENINFO_ENDPOINT}",
        "userinfo_uri": "${OIDC_USERINFO_ENDPOINT}"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: hhb-database-secrets
  labels:
    name: hhb-database-secrets
stringData:
  POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
  POSTGRESQL_PASSWORD_BKTSVC: ${POSTGRESQL_PASSWORD_BKTSVC}
  POSTGRESQL_PASSWORD_GRBSVC: ${POSTGRESQL_PASSWORD_GRBSVC}
  POSTGRESQL_PASSWORD_HHBSVC: ${POSTGRESQL_PASSWORD_HHBSVC}
  POSTGRESQL_PASSWORD_LOGSVC: ${POSTGRESQL_PASSWORD_LOGSVC}
  POSTGRESQL_PASSWORD_ORGSVC: ${POSTGRESQL_PASSWORD_ORGSVC}
  HHB_DATABASE_URL: "postgresql://hhbsvc:$POSTGRESQL_PASSWORD_HHBSVC@hhb-database/huishoudboekjeservice"
  GROOTBOEK_DATABASE_URL: "postgresql://grbsvc:$POSTGRESQL_PASSWORD_GRBSVC@hhb-database/grootboekservice"
  LOG_DATABASE_URL: "postgresql://logsvc:$POSTGRESQL_PASSWORD_LOGSVC@hhb-database/logservice"
  ORGANISATIE_DATABASE_URL: "postgresql://orgsvc:$POSTGRESQL_PASSWORD_ORGSVC@hhb-database/organisatieservice"
  TRANSACTIE_DATABASE_URL: "postgresql://bktsvc:$POSTGRESQL_PASSWORD_BKTSVC@hhb-database/banktransactieservice"
