apiVersion: v1
kind: Secret
metadata:
  name: hhb-database-secrets
  labels:
    name: hhb-database-secrets
stringData:
  POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
  POSTGRESQL_PASSWORD_BKTSVC: ${POSTGRESQL_PASSWORD_BKTSVC}
  POSTGRESQL_PASSWORD_GRBSVC: ${POSTGRESQL_PASSWORD_GRBSVC}
  POSTGRESQL_PASSWORD_HHBSVC: ${POSTGRESQL_PASSWORD_HHBSVC}
  POSTGRESQL_PASSWORD_LOGSVC: ${POSTGRESQL_PASSWORD_LOGSVC}
  POSTGRESQL_PASSWORD_ORGSVC: ${POSTGRESQL_PASSWORD_ORGSVC}
  POSTGRESQL_PASSWORD_PADSVC: ${POSTGRESQL_PASSWORD_PADSVC}
  POSTGRESQL_PASSWORD_ALMSVC: ${POSTGRESQL_PASSWORD_ALMSVC}
  POSTGRESQL_PASSWORD_SIGSVC: ${POSTGRESQL_PASSWORD_SIGSVC}

  HUISHOUDBOEKJESERVICE_DATABASE_URL: "postgresql://$POSTGRESQL_USERNAME_HHBSVC:$POSTGRESQL_PASSWORD_HHBSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_HHBSVC"
  GROOTBOEKSERVICE_DATABASE_URL: "postgresql://$POSTGRESQL_USERNAME_GRBSVC:$POSTGRESQL_PASSWORD_GRBSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_GRBSVC"
  LOGSERVICE_DATABASE_URL: "postgresql://$POSTGRESQL_USERNAME_LOGSVC:$POSTGRESQL_PASSWORD_LOGSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_LOGSVC"
  ORGANISATIESERVICE_DATABASE_URL: "postgresql://$POSTGRESQL_USERNAME_ORGSVC:$POSTGRESQL_PASSWORD_ORGSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_ORGSVC"
  TRANSACTIESERVICE_DATABASE_URL: "postgresql://$POSTGRESQL_USERNAME_BKTSVC:$POSTGRESQL_PASSWORD_BKTSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_BKTSVC"
  POSTADRESSENSERVICE_DATABASE_URL: "postgresql://$POSTGRESQL_USERNAME_PADSVC:$POSTGRESQL_PASSWORD_PADSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_PADSVC"
  ALARMENSERVICE_DATABASE_URL: "postgresql://$POSTGRESQL_USERNAME_ALMSVC:$POSTGRESQL_PASSWORD_ALMSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_ALMSVC"
  SIGNALENSERVICE_DATABASE_URL: "postgresql://$POSTGRESQL_USERNAME_SIGSVC:$POSTGRESQL_PASSWORD_SIGSVC@$POSTGRESQL_HOSTNAME:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE_NAME_SIGSVC"
