---
# TODO deze moet per omgeving
apiVersion: v1
kind: Secret
metadata:
  name: hhb-dex-secrets
  labels:
    name: hhb-dex-secrets
stringData:
  config.yaml: |-
    issuer: ${HHB_DEX_ENDPOINT}
    storage:
      config:
        file: ':memory:'
        inCluster: true
      type: sqlite3
    logger:
      level: info
    web:
      http: 0.0.0.0:5556
    oauth2:
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    staticClients:
      - id: huishoudboekje
        name: Huishoudboekje Schaalbaar
        redirectURIs:
          - "${HHB_API_ENDPOINT}/oidc_callback"
        secret: ${HHB_SECRET}
    staticPasswords:
    - userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
      username: "koen@openweb.nl"
      email: "koen@openweb.nl"
      hash: "$2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa"
    - userID: "18a8684b-db88-4b73-90a9-3cd1661f5466"
      username: "magre"
      email: "bas.magre@topicus.nl"
      hash: "$2a$12$2hU8hddPgKYCawent4C0VeH.YDxr3KLqZYASESpxlz7AHhZJoBQWq"
    enablePasswordDB: true
    expiry:
      idTokens: 168h
---
apiVersion: v1
kind: Secret
metadata:
  name: hhb-client-secrets
  labels:
    name: hhb-client-secrets
stringData:
  SECRET_KEY: ${HHB_SECRET}
  client_secrets.json: |
    {
      "web": {
        "mark": true,
        "auth_uri": "${HHB_DEX_ENDPOINT}/auth",
        "client_id": "huishoudboekje",
        "client_secret": "${HHB_SECRET}",
        "issuer": "${HHB_DEX_ENDPOINT}",
        "redirect_uris":
          [
              "${HHB_API_ENDPOINT}/oidc_callback"
          ],
        "token_uri": "${HHB_DEX_ENDPOINT}/token",
        "token_introspection_uri": "${HHB_DEX_ENDPOINT}/tokeninfo",
        "userinfo_uri": "${HHB_DEX_ENDPOINT}/userinfo"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: hhb-database-secrets
  labels:
    name: hhb-database-secrets
stringData:
  POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
  POSTGRESQL_PASSWORD_BKTSVC: ${POSTGRESQL_PASSWORD_BKTSVC}
  POSTGRESQL_PASSWORD_GRBSVC: ${POSTGRESQL_PASSWORD_GRBSVC}
  POSTGRESQL_PASSWORD_HHBSVC: ${POSTGRESQL_PASSWORD_HHBSVC}
  POSTGRESQL_PASSWORD_LOGSVC: ${POSTGRESQL_PASSWORD_LOGSVC}
  POSTGRESQL_PASSWORD_ORGSVC: ${POSTGRESQL_PASSWORD_ORGSVC}
  HHB_DATABASE_URL: "postgresql://hhbsvc:$POSTGRESQL_PASSWORD_HHBSVC@hhb-database/huishoudboekjeservice"
  GROOTBOEK_DATABASE_URL: "postgresql://grbsvc:$POSTGRESQL_PASSWORD_GRBSVC@hhb-database/grootboekservice"
  LOG_DATABASE_URL: "postgresql://logsvc:$POSTGRESQL_PASSWORD_LOGSVC@hhb-database/logservice"
  ORGANISATIE_DATABASE_URL: "postgresql://orgsvc:$POSTGRESQL_PASSWORD_ORGSVC@hhb-database/organisatieservice"
  TRANSACTIE_DATABASE_URL: "postgresql://bktsvc:$POSTGRESQL_PASSWORD_BKTSVC@hhb-database/banktransactieservice"
