---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: hhb-database-volume
spec:
  storageClassName: ${STORAGECLASSNAME}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hhb-database-volumeclaim
spec:
  storageClassName: ${STORAGECLASSNAME}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-dex-ingress
spec:
  tls:
    - hosts:
        - ${HHB_DEX_DNS}
      secretName: dex-ingress-tls
  rules:
    - host: ${HHB_DEX_DNS}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hhb-dex
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-frontend
spec:
  tls:
    - hosts:
        - ${HHB_FRONTEND_DNS}
      secretName: hhb-frontend-ingress-tls
  rules:
    - host: ${HHB_FRONTEND_DNS}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hhb-frontend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-backend-ingress
spec:
  tls:
    - hosts: 
        - ${HHB_FRONTEND_DNS}
      secretName: hhb-medewerker-backend-ingress-tls
  rules:
    - host: ${HHB_FRONTEND_DNS}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hhb-backend
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hhb-unleashservice
spec:
  tls:
    - hosts:
        - ${HHB_HOST}
      secretName: hhb-unleashservice-ingress-tls
  rules:
    - host: ${HHB_HOST}
      http:
        paths:
          - path: /api/unleash
            pathType: Prefix
            backend:
              service:
                name: hhb-unleashservice
                port:
                  number: 80
