---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  labels:
    name: keycloak-config
data:
  DB_DATABASE: ${KEYCLOAK_DB_DATABASE}
  DB_USER: ${KEYCLOAK_DB_USER}
  DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
  KEYCLOAK_AUTH_KEYCLOAK_URL: ${KEYCLOAK_AUTH_KEYCLOAK_URL}
  KEYCLOAK_CLIENT_ROOT_URL: ${KEYCLOAK_CLIENT_ROOT_URL}
  KEYCLOAK_AUTH_USERNAME: ${KEYCLOAK_AUTH_USERNAME}
