---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-keycloak
spec:
  template:
    spec:
      containers:
        - name: hhb-keycloak
          env:
            - name: KEYCLOAK_FRONTEND_URL
              value: "https://${HHB_FRONTEND_DNS}/auth"