---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-keycloak
spec:
  template:
    spec:
      containers:
        - name: hhb-keycloak
          env:
            - name: KEYCLOAK_FRONTEND_URL
              value: "https://${HHB_FRONTEND_DNS}/auth"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-frontend
  labels:
    name: hhb-frontend
spec:
  template:
    spec:
      volumes:
        - name: keycloak-init-env
          emptyDir: {}
        - name: keycloak-init-script
          configMap:
            name: hhb-keycloak-init-script
      initContainers:
        - name: init-keycloak
          image: bitnami/python:3.8
          imagePullPolicy: IfNotPresent
          command:
            [
              "bash",
              "-c",
              "cd env &&",
              "virtualenv keycloak_init -p python3 &&",
              "source keycloak_init/bin/activate &&",
              "python3 -m pip install -r ../script/requirements.txt &&",
              "python3 ../script/keycloak_hhb.py"
            ]
          env:
            - name: KEYCLOAK_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hhb-keycloak-secrets
                  key: KEYCLOAK_AUTH_USERNAME
            - name: KEYCLOAK_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hhb-keycloak-secrets
                  key: KEYCLOAK_AUTH_PASSWORD
            - name: KEYCLOAK_AUTH_KEYCLOAK_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-keycloak-secrets
                  key: KEYCLOAK_AUTH_KEYCLOAK_URL
            - name: KEYCLOAK_CLIENT_ROOT_URL
              valueFrom:
                secretKeyRef:
                  name: hhb-keycloak-secrets
                  key: KEYCLOAK_CLIENT_ROOT_URL
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hhb-keycloak-secrets
                  key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_CLIENT_USERS
              valueFrom:
                secretKeyRef:
                  name: hhb-keycloak-secrets
                  key: KEYCLOAK_CLIENT_USERS
          volumeMounts:
            - name: keycloak-init-script
              mountPath: /app/script
            - name: keycloak-init-env
              mountPath: /app/env
