---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-rapportageservice
  labels:
    name: hhb-rapportageservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-rapportageservice
  template:
    metadata:
      labels:
        name: hhb-rapportageservice
    spec:
      initContainers:
      containers:
        - name: hhb-rapportageservice
          image: rapportageservice
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: "300m"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: HHB_SERVICE_URL
              value: "http://hhb-huishoudboekjeservice"
            - name: TRANSACTIE_SERVICE_URL
              value: "http://hhb-banktransactieservice"
            - name: LOG_LEVEL
              value: INFO
            - name: STATSD_HOST
              value: "hhb-statsd-exporter:9125"
            - name: RABBITMQ_HOST
              value: hhb-rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASS
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_PASS