---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-rapportageserviceservice
  labels:
    name: hhb-rapportageserviceservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-rapportageserviceservice
  template:
    metadata:
      labels:
        name: hhb-rapportageserviceservice
    spec:
      initContainers:
      containers:
        - name: hhb-rapportageserviceservice
          image: rapportageservice
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          env:
            - name: HHB_SERVICE_URL
              value: "http://hhb-huishoudboekjeservice"
            - name: TRANSACTIE_SERVICE_URL
              value: "http://hhb-banktransactieservice"