---
apiVersion: v1
kind: Service
metadata:
  name: hhb-rapportageserviceservice
  labels:
    name: hhb-rapportageserviceservice
spec:
  type: ClusterIP
  selector:
    name: hhb-rapportageserviceservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
