"""add transaction index

Revision ID: 05e42c2d4533
Revises: ff65ebc48098
Create Date: 2021-02-16 21:13:43.252055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e42c2d4533'
down_revision = 'ff65ebc48098'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_journaalposten_transaction_id'), 'journaalposten', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journaalposten_transaction_id'), table_name='journaalposten')
    # ### end Alembic commands ###
