"""add automatische incasso

Revision ID: 12b7c5007ec2
Revises: 43baa9e8e9fc
Create Date: 2020-11-30 13:26:39.276600

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '12b7c5007ec2'
down_revision = '43baa9e8e9fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('automatische_incasso', sa.Boolean(), nullable=True))
    connection = op.get_bind()
    t_afspraken = sa.Table(
        'afspraken',
        sa.MetaData(),
        sa.Column('credit', sa.Boolean(), nullable=True),
        sa.Column('automatische_incasso', sa.Boolean(), nullable=True),
    )
    connection.execute(
        t_afspraken.update().where(t_afspraken.c.credit == False).values(automatische_incasso=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('afspraken', 'automatische_incasso')
    # ### end Alembic commands ###
