"""remove burger and add fields to gebruiker

Revision ID: 1317cfeb179a
Revises: ce1b21aa825f
Create Date: 2020-10-14 13:35:15.554756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1317cfeb179a'
down_revision = 'ce1b21aa825f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burgers')
    op.add_column('gebruikers', sa.Column('achternaam', sa.String(), nullable=True))
    op.add_column('gebruikers', sa.Column('huisnummer', sa.String(), nullable=True))
    op.add_column('gebruikers', sa.Column('postcode', sa.String(), nullable=True))
    op.add_column('gebruikers', sa.Column('straatnaam', sa.String(), nullable=True))
    op.add_column('gebruikers', sa.Column('voorletters', sa.String(), nullable=True))
    op.add_column('gebruikers', sa.Column('voornamen', sa.String(), nullable=True))
    op.add_column('gebruikers', sa.Column('woonplaatsnaam', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gebruikers', 'woonplaatsnaam')
    op.drop_column('gebruikers', 'voornamen')
    op.drop_column('gebruikers', 'voorletters')
    op.drop_column('gebruikers', 'straatnaam')
    op.drop_column('gebruikers', 'postcode')
    op.drop_column('gebruikers', 'huisnummer')
    op.drop_column('gebruikers', 'achternaam')
    op.create_table('burgers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gebruiker_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voornamen', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('voorletters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('straatnaam', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('woonplaatsnaam', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('achternaam', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('huisnummer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gebruiker_id'], ['gebruikers.id'], name='burgers_gebruiker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='burgers_pkey')
    )
    # ### end Alembic commands ###
