"""empty message

Revision ID: 1fd976dba062
Revises: b7eaefa6ef73
Create Date: 2023-03-28 13:02:00.483377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd976dba062'
down_revision = 'b7eaefa6ef73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saldos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('burger_id', sa.Integer(), nullable=False),
    sa.Column('begindatum', sa.DateTime(), nullable=True),
    sa.Column('einddatum', sa.DateTime(), nullable=True),
    sa.Column('saldo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['burger_id'], ['burgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos')
    # ### end Alembic commands ###
