"""empty message

Revision ID: 21f926df8533
Revises: aaa8b8610272
Create Date: 2021-08-03 15:42:14.433118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f926df8533'
down_revision = 'aaa8b8610272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisaties', 'vestigingsnummer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisaties', sa.Column('vestigingsnummer', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
