"""added rekening table

Revision ID: 22ed5017fa8a
Revises: 41b64919bfb4
Create Date: 2020-10-23 15:53:31.608879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ed5017fa8a'
down_revision = 'f53e311ed706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rekeningen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(100), nullable=False),
    sa.Column('rekeninghouder', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rekening_gebruiker',
    sa.Column('rekening_id', sa.Integer(), nullable=False),
    sa.Column('gebruiker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gebruiker_id'], ['gebruikers.id'], ),
    sa.ForeignKeyConstraint(['rekening_id'], ['rekeningen.id'], ),
    sa.PrimaryKeyConstraint('rekening_id', 'gebruiker_id')
    )
    op.create_table('rekening_organisatie',
    sa.Column('rekening_id', sa.Integer(), nullable=False),
    sa.Column('organisatie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], ),
    sa.ForeignKeyConstraint(['rekening_id'], ['rekeningen.id'], ),
    sa.PrimaryKeyConstraint('rekening_id', 'organisatie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rekening_organisatie_tabel')
    op.drop_table('rekening_gebruiker_tabel')
    op.drop_table('rekening')
    # ### end Alembic commands ###
