"""empty message

Revision ID: 2d479f99ec87
Revises: 84f7036b03d7
Create Date: 2021-10-18 12:37:12.587723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d479f99ec87'
down_revision = '84f7036b03d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('postadres_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('afspraken', 'postadres_id')
    # ### end Alembic commands ###
