"""configuratie

Revision ID: 2db81b1fda15
Revises: 12b7c5007ec2
Create Date: 2020-12-03 09:02:56.783531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db81b1fda15'
down_revision = '12b7c5007ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuratie',
    sa.Column('id', sa.String(), sa.CheckConstraint("id ~ '^[a-zA-Z0-9_]+$'"), nullable=False),
    sa.Column('waarde', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuratie')
    # ### end Alembic commands ###
