"""empty message

Revision ID: 3051f9101b6d
Revises: 2a8bdc5eb90d
Create Date: 2021-07-27 10:41:12.768008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3051f9101b6d'
down_revision = '2a8bdc5eb90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('sha256', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'sha256')
    # ### end Alembic commands ###
