"""Add organisation_id to afspraak

Revision ID: 3a2fa07ad645
Revises: 8ba2a1cb0cf4
Create Date: 2020-11-11 14:15:01.325759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2fa07ad645'
down_revision = '8ba2a1cb0cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('organisatie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'afspraken', 'organisaties', ['organisatie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'afspraken', type_='foreignkey')
    op.drop_column('afspraken', 'organisatie_id')
    # ### end Alembic commands ###
