"""Grootboekrekening_id must be unique

Revision ID: 3d83f1e7af50
Revises: 7b0c4fb515d1
Create Date: 2021-02-02 17:15:24.970398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d83f1e7af50'
down_revision = '7b0c4fb515d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rubrieken', ['grootboekrekening_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rubrieken', type_='unique')
    # ### end Alembic commands ###
