"""empty message

Revision ID: 4de4b55e5e06
Revises: 8f466f7d5f4c
Create Date: 2023-03-27 09:44:28.740380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de4b55e5e06'
down_revision = '8f466f7d5f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('burgers', sa.Column('saldo', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('burgers', 'saldo')
    # ### end Alembic commands ###
