"""empty message

Revision ID: 5c957bd21888
Revises: 871d1f0e3ce4
Create Date: 2021-09-03 13:59:01.456598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c957bd21888'
down_revision = '871d1f0e3ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rekening_afdeling', 'afdelingen', ['afdeling_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rekening_afdeling', type_='foreignkey')
    # ### end Alembic commands ###
