"""empty message

Revision ID: 65fd104756c0
Revises: e96955415ec1
Create Date: 2024-06-11 13:47:25.160823

"""
from datetime import datetime
from time import time
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fd104756c0'
down_revision = 'e96955415ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burgers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('start_date', sa.BigInteger(), default=time))

    connection = op.get_bind()

    content = connection.execute(sa.text(
        f"SELECT min(valid_from), burger_id FROM afspraken WHERE burger_id IS NOT NULL GROUP BY burger_id ORDER BY burger_id")).fetchall()

    for row in content:
        # dt = datetime.fromisoformat(row[0])
        unix = row[0].timestamp()
        connection.execute(sa.text(
            f"UPDATE burgers SET start_date= {unix} WHERE id = {row[1]}"))

    now = datetime.now().timestamp()

    connection.execute(sa.text(
        f"UPDATE burgers SET start_date = {now} WHERE start_date IS NULL"
    ))

    op.alter_column('burgers', 'start_date', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('burgers', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
