"""empty message

Revision ID: 724865f799bc
Revises: 21f926df8533
Create Date: 2021-08-03 15:54:12.476330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724865f799bc'
down_revision = '21f926df8533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisaties', sa.Column('vestigingsnummer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisaties', 'vestigingsnummer')
    # ### end Alembic commands ###
