"""added start, einddatum and xmldata fields for export table

Revision ID: 7b0c4fb515d1
Revises: 132fb7c5671c
Create Date: 2021-01-12 11:51:08.977327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0c4fb515d1'
down_revision = '132fb7c5671c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export', sa.Column('eind_datum', sa.Date(), nullable=True))
    op.add_column('export', sa.Column('start_datum', sa.Date(), nullable=True))
    op.add_column('export', sa.Column('xmldata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export', 'xmldata')
    op.drop_column('export', 'start_datum')
    op.drop_column('export', 'eind_datum')
    # ### end Alembic commands ###
