"""empty message

Revision ID: 84f7036b03d7
Revises: b9bdb396ade5
Create Date: 2021-09-19 10:58:20.555941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f7036b03d7'
down_revision = 'b9bdb396ade5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'afspraken', 'afdelingen', ['afdeling_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'afspraken', type_='foreignkey')
    # ### end Alembic commands ###
