"""empty message

Revision ID: 871d1f0e3ce4
Revises: bd2993e25d65
Create Date: 2021-09-03 13:25:10.773421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871d1f0e3ce4'
down_revision = 'bd2993e25d65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('afdelingen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rekening_afdeling',
    sa.Column('rekening_id', sa.Integer(), nullable=False),
    sa.Column('afdeling_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rekening_id'], ['rekeningen.id'], ),
    sa.PrimaryKeyConstraint('rekening_id', 'afdeling_id')
    )
    op.drop_index('ix_afspraken_organisatie_id', table_name='afspraken')
    op.drop_column('afspraken', 'organisatie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('organisatie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_afspraken_organisatie_id', 'afspraken', ['organisatie_id'], unique=False)
    op.drop_table('rekening_afdeling')
    op.drop_table('afdelingen')
    # ### end Alembic commands ###
