"""Added grootboekrekening_id to Afspraak

Revision ID: 8b51c695f3c2
Revises: 3a2fa07ad645
Create Date: 2020-11-19 11:52:22.042400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b51c695f3c2'
down_revision = '045a7bdd1739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('grootboekrekening_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('afspraken', 'grootboekrekening_id')
    # ### end Alembic commands ###
