"""fixed typo in column name

Revision ID: 8ba2a1cb0cf4
Revises: 41b64919bfb4
Create Date: 2020-10-29 12:14:18.462045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba2a1cb0cf4'
down_revision = '41b64919bfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('beschrijving', sa.String(), nullable=True))
    op.drop_column('afspraken', 'beschijving')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('beschijving', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('afspraken', 'beschrijving')
    # ### end Alembic commands ###
