"""empty message

Revision ID: aaa8b8610272
Revises: 3051f9101b6d
Create Date: 2021-08-03 15:29:48.848914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa8b8610272'
down_revision = 'd4258041047d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisaties', sa.Column('vestigingsnummer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisaties', 'vestigingsnummer')
    # ### end Alembic commands ###
