"""removed interval, added betaalinstructie to afspraak.

Revision ID: b516f0abf35d
Revises: cd505e0d103b
Create Date: 2021-04-15 13:37:38.239465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b516f0abf35d'
down_revision = 'cd505e0d103b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('betaalinstructie', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    op.drop_column('afspraken', 'interval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('interval', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('afspraken', 'betaalinstructie')
    # ### end Alembic commands ###
