"""Removed IBAN from burgers

Revision ID: b7a89ea6f6ed
Revises: d5ff83b140d1
Create Date: 2022-09-14 15:42:30.569749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a89ea6f6ed'
down_revision = 'd5ff83b140d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('burgers', 'iban')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('burgers', sa.Column('iban', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
