"""empty message

Revision ID: b7eaefa6ef73
Revises: 8f466f7d5f4c
Create Date: 2023-03-28 09:00:32.861278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7eaefa6ef73'
down_revision = '8f466f7d5f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('burgers', sa.Column('saldo', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('burgers', 'saldo')
    # ### end Alembic commands ###
