"""renamed gebruikers to burgers

Revision ID: bb34d4687553
Revises: 05e42c2d4533
Create Date: 2021-02-25 15:33:12.919063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb34d4687553'
down_revision = '05e42c2d4533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('gebruikers', 'burgers')
    op.execute('ALTER SEQUENCE gebruikers_id_seq RENAME TO burgers_id_seq;')

    op.rename_table('rekening_gebruiker', 'rekening_burger')
    op.alter_column('rekening_burger', 'gebruiker_id', new_column_name='burger_id')
    op.alter_column('afspraken', 'gebruiker_id', new_column_name='burger_id')

    op.drop_constraint('afspraken_gebruiker_id_fkey', 'afspraken', type_='foreignkey')
    op.drop_constraint('rekening_gebruiker_gebruiker_id_fkey', 'rekening_burger', type_='foreignkey')
    op.drop_constraint('rekening_gebruiker_rekening_id_fkey', 'rekening_burger', type_='foreignkey')
    op.drop_constraint('rekening_gebruiker_pkey', 'rekening_burger', type_='primary')
    op.drop_constraint('gebruikers_pkey', 'burgers', type_='primary')

    op.create_primary_key("burgers_pkey", 'burgers', ['id'])
    op.create_primary_key("rekening_burger_pkey", 'rekening_burger', ['rekening_id', 'burger_id'])

    op.create_foreign_key(None, 'rekening_burger', 'burgers', ['burger_id'], ['id'])
    op.create_foreign_key(None, 'rekening_burger', 'rekeningen', ['rekening_id'], ['id'])
    op.create_foreign_key(None, 'afspraken', 'burgers', ['burger_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    op.rename_table('burgers', 'gebruikers')
    op.execute('ALTER SEQUENCE burgers_id_seq RENAME TO gebruikers_id_seq;')

    op.rename_table('rekening_burger', 'rekening_gebruiker')
    op.alter_column('rekening_gebruiker', 'burger_id', new_column_name='gebruiker_id')
    op.alter_column('afspraken', 'burger_id', new_column_name='gebruiker_id')

    op.drop_constraint('afspraken_burger_id_fkey', 'afspraken', type_='foreignkey')
    op.drop_constraint('rekening_burger_burger_id_fkey', 'rekening_gebruiker', type_='foreignkey')
    op.drop_constraint('rekening_burger_rekening_id_fkey', 'rekening_gebruiker', type_='foreignkey')
    op.drop_constraint('rekening_burger_pkey', 'rekening_gebruiker', type_='primary')
    op.drop_constraint('burgers_pkey', 'gebruikers', type_='primary')

    op.create_primary_key("gebruikers_pkey", 'gebruikers', ['id'])
    op.create_primary_key("rekening_gebruiker_pkey", 'rekening_gebruiker', ['rekening_id', 'gebruiker_id'])

    op.create_foreign_key(None, 'rekening_gebruiker', 'gebruikers', ['gebruiker_id'], ['id'])
    op.create_foreign_key(None, 'rekening_gebruiker', 'rekeningen', ['rekening_id'], ['id'])
    op.create_foreign_key(None, 'afspraken', 'gebruikers', ['gebruiker_id'], ['id'])
