"""empty message

Revision ID: bd2993e25d65
Revises: e8b8e7ff1eec
Create Date: 2021-08-25 16:36:55.317722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2993e25d65'
down_revision = 'e8b8e7ff1eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('organisatie_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_afspraken_organisatie_id'), 'afspraken', ['organisatie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_afspraken_organisatie_id'), table_name='afspraken')
    op.drop_column('afspraken', 'organisatie_id')
    # ### end Alembic commands ###
