"""Added iban and weergave_naam also moved elements from database to core

Revision ID: ce1b21aa825f
Revises: b25eb2556ad3
Create Date: 2020-10-08 15:46:31.182446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1b21aa825f'
down_revision = 'b25eb2556ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gebruikers', sa.Column('iban', sa.String(), nullable=True))
    op.add_column('gebruikers', sa.Column('weergave_naam', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gebruikers', 'weergave_naam')
    op.drop_column('gebruikers', 'iban')
    # ### end Alembic commands ###
