"""add alarm id to afspraak

Revision ID: d5ff83b140d1
Revises: 2d479f99ec87
Create Date: 2021-12-14 14:09:47.724918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ff83b140d1'
down_revision = '2d479f99ec87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('alarm_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('afspraken', 'alarm_id')
    # ### end Alembic commands ###
