"""Added overschrgit staijving tabel

Revision ID: dbbfa0d519b6
Revises: 12b7c5007ec2
Create Date: 2020-12-03 14:45:08.471569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbfa0d519b6'
down_revision = '12b7c5007ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overschrijvingen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('afspraak_id', sa.Integer(), nullable=True),
    sa.Column('export_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=True),
    sa.Column('bedrag', sa.Integer(), nullable=True),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['afspraak_id'], ['afspraken.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overschrijvingen')
    # ### end Alembic commands ###
