"""empty message

Revision ID: e70db1cbbc3e
Revises: f99d4fa94545
Create Date: 2021-08-03 12:13:09.989505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70db1cbbc3e'
down_revision = 'f99d4fa94545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('burgers', 'bsn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('burgers', sa.Column('bsn', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
