"""empty message

Revision ID: e8b8e7ff1eec
Revises: 573881541fb4
Create Date: 2021-08-25 16:12:53.574575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b8e7ff1eec'
down_revision = '573881541fb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('afspraken_organisatie_id_fkey', 'afspraken',
                       type_='foreignkey')
    op.drop_table('rekening_organisatie')
    op.drop_table('organisaties')
    op.drop_index('ix_afspraken_organisatie_id', table_name='afspraken')
    op.drop_column('afspraken', 'organisatie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afspraken', sa.Column('organisatie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('afspraken_organisatie_id_fkey', 'afspraken', 'organisaties', ['organisatie_id'], ['id'])
    op.create_index('ix_afspraken_organisatie_id', 'afspraken', ['organisatie_id'], unique=False)
    op.create_table('rekening_organisatie',
    sa.Column('rekening_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organisatie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organisatie_id'], ['organisaties.id'], name='rekening_organisatie_organisatie_id_fkey'),
    sa.ForeignKeyConstraint(['rekening_id'], ['rekeningen.id'], name='rekening_organisatie_rekening_id_fkey'),
    sa.PrimaryKeyConstraint('rekening_id', 'organisatie_id', name='rekening_organisatie_pkey')
    )
    op.create_table('organisaties',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organisaties_pkey')
    )
    # ### end Alembic commands ###
