"""Added Organisatie element

Revision ID: f53e311ed706
Revises: ce1b21aa825f
Create Date: 2020-10-13 13:54:24.024569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53e311ed706'
down_revision = 'abdbb3479921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisaties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weergave_naam', sa.String(), nullable=True),
    sa.Column('kvk_nummer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organisaties')
    # ### end Alembic commands ###
