"""empty message

Revision ID: fa782fdde1a6
Revises: 5c957bd21888
Create Date: 2021-09-03 14:29:18.743755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa782fdde1a6'
down_revision = '5c957bd21888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('afdelingen', sa.Column('organisatie_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('afdelingen', 'organisatie_id')
    # ### end Alembic commands ###
