"""added boolean for automatic boeking on journaalpost

Revision ID: ff65ebc48098
Revises: 2c76e4f17832
Create Date: 2021-02-09 14:00:44.452604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff65ebc48098'
down_revision = '2c76e4f17832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journaalposten', sa.Column('is_automatisch_geboekt', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journaalposten', 'is_automatisch_geboekt')
    # ### end Alembic commands ###
