
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: hhb.minikube
      paths:
        - "/api/"
  tls: []

oidc:
  issuer: http://dex.hhb.minikube
  client: huishoudboekje
  secret: ZwwcL2zjQyJUBnFPVoOb
  authorizationEndpoint: http://dex.hhb.minikube/auth
  redirectUri: http://hhb.minikube/api/oidc_callback
  tokenUri: http://dex.hhb.minikube/token
  tokenInfoUri: http://dex.hhb.minikube/tokenInfo
