{{- $databaseName := include "database.databasename" . -}}
{{- $databaseLabels := include "database.labels" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $databaseName "init-scripts" | trunc 63 | trimSuffix "-" | quote }}
  labels:
  {{- $databaseLabels | nindent 4 }}
type: Opaque
stringData:
  01_service_databases.sql: |
{{- range $database := .Values.databases }}
    CREATE USER "{{ $database }}" WITH PASSWORD '{{ $database }}';
    CREATE DATABASE {{ $database }} WITH OWNER {{ $database }};
{{- end -}}

{{- range $database := .Values.databases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $databaseName $database | replace "_" "-" | trunc 63 | trimSuffix "-" | quote }}
  labels:
  {{- $databaseLabels | nindent 4 }}
type: Opaque
stringData:
  username: {{ printf "%s" $database | quote }}
  password: {{ printf "%s" $database | quote }}
{{- end -}}
