{{- $databaseName := include "database.name" . -}}
{{- $databaseLabels := include "database.labels" . -}}
{{- define "service.database" -}}
{{- . | replace "_" "" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $databaseName "init-scripts" | trunc 63 | trimSuffix "-" | quote }}
  labels:
  {{- $databaseLabels | nindent 4 }}
type: Opaque
stringData:
  01_service_databases.sql: |
{{- range $service := .Values.services }}
  {{- $database := include "service.database" $service }}
    CREATE USER "{{ $database }}" WITH PASSWORD '{{ $database }}';
    CREATE DATABASE "{{ $database }}" WITH OWNER "{{ $database }}";
{{- end -}}

{{- range $service := .Values.services }}
{{- $database := include "service.database" $service }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $databaseName $service | replace "_" "-" | trunc 63 | trimSuffix "-" | quote }}
  labels:
  {{- $databaseLabels | nindent 4 }}
type: Opaque
stringData:
  database: {{ $database | quote }}
  username: {{ $database | quote }}
  password: {{ $database | quote }}
{{- end -}}
