{{- $databaseName := include "database.name" . -}}
{{- $databaseLabels := include "database.labels" . -}}
{{- define "service.database" -}}
{{- . | replace "_" "" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $databaseName "init-scripts" | trunc 63 | trimSuffix "-" | quote }}
  labels:
  {{- $databaseLabels | nindent 4 }}
type: Opaque
stringData:
  01_service_databases.sql: |
{{- range $service := .Values.services }}
  {{- $database := include "service.database" $service }}
    SELECT 'CREATE USER {{ $database }}' WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '{{ $database }}')\gexec
    SELECT 'CREATE DATABASE {{ $database }}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ $database }}')\gexec
    ALTER ROLE "{{ $database }}" WITH PASSWORD '{{ $database }}';
    ALTER DATABASE "{{ $database }}" OWNER TO "{{ $database }}";
{{- end -}}

{{- range $service := .Values.services }}
{{- $database := include "service.database" $service }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $databaseName $service | replace "_" "-" | trunc 63 | trimSuffix "-" | quote }}
  labels:
  {{- $databaseLabels | nindent 4 }}
type: Opaque
stringData:
  database: {{ $database | quote }}
  username: {{ $database | quote }}
  password: {{ $database | quote }}
{{- end -}}
