---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-backend
spec:
  template:
    spec:
      containers:
        - name: hhb-backend
          env:
            - name: APP_SETTINGS
              value: "hhb_backend.config.LocalConfig" # OIDC_ID_TOKEN_COOKIE_SECURE = False
            - name: AUTH_AUDIENCE
              value: http://${HHB_APP_HOST} # http not https
---
apiVersion: v1
kind: Secret
metadata:
  name: hhb-client-secrets
stringData:
  SECRET_KEY: test
  client_secrets.json: |
    {
      "web": {
        "mark": true,
        "auth_uri": "http://${HHB_APP_HOST}/dex/auth",
        "client_id": "huishoudboekje",
        "client_secret": "test",
        "issuer": "http://${HHB_APP_HOST}/dex",
        "redirect_uris":
          [
              "http://${HHB_APP_HOST}/api/oidc_callback",
              "http://hhb-backend/oidc_callback"
          ],
        "token_uri": "http://hhb-dex/dex/token",
        "token_introspection_uri": "http://hhb-dex/dex/tokeninfo",
        "userinfo_uri": "http://hhb-dex/dex/userinfo"
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: hhb-dex-secrets
stringData:
  config.yaml: |-
    issuer: http://${HHB_APP_HOST}/dex
    storage:
      config:
        file: ':memory:'
        inCluster: true
      type: sqlite3
    logger:
      level: info
    web:
      http: 0.0.0.0:5556
    oauth2:
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    staticClients:
      - id: huishoudboekje
        name: Huishoudboekje Schaalbaar
        redirectURIs:
          - "http://${HHB_APP_HOST}/api/oidc_callback"
          - "http://hhb-backend/oidc_callback"
        secret: test
    staticPasswords:
    - userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
      username: "koen@openweb.nl"
      email: "koen@openweb.nl"
      hash: "$2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa"
    - userID: "18a8684b-db88-4b73-90a9-3cd1661f5466"
      username: "magre"
      email: "bas.magre@topicus.nl"
      hash: "$2a$12$2hU8hddPgKYCawent4C0VeH.YDxr3KLqZYASESpxlz7AHhZJoBQWq"
    - username: henk.poortvliet@sloothuizen.nl
      email: henk.poortvliet@sloothuizen.nl
      name: Henk Poortvliet
      userID: 363283b9-07bb-4247-bfe4-977a1e221cc4
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: bauke.huijbers@vng.nl
      email: bauke.huijbers@vng.nl
      name: Bauke Huijbers
      userID: bcfe94b8-fc0e-48d8-ada7-c04f96d31e18
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: huishoudboekje010@rotterdam.nl
      email: huishoudboekje010@rotterdam.nl
      name: Gemeente Rotterdam
      userID: 397c2959-e692-42fa-ae54-fad84f4d256e
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: huishoudboekje@utrecht.nl
      email: huishoudboekje@utrecht.nl
      name: Gemeente Utrecht
      userID: 41e2bb72-f62d-44c1-ae0c-b1190892db50
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: nerds@sloothuizen.nl
      email: nerds@sloothuizen.nl
      name: Nerds Company
      userID: da072226-ce83-11eb-b8bc-0242ac130003
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    - username: wouter.brunekreeft@topicus.nl
      email: wouter.brunekreeft@topicus.nl
      name: Wouter Brunekreeft
      userID: ptn38526-0g8d-vnk8-nsv3-sdnvj294fjvn
      hash: $2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa # demo
    enablePasswordDB: true
    expiry:
      idTokens: 168h
