"""empty message

Revision ID: 0e9c58c75475
Revises: a4a7a0dd3bd6
Create Date: 2020-09-29 14:52:29.840321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9c58c75475'
down_revision = 'a4a7a0dd3bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('burgers', sa.Column('gebruiker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'burgers', 'gebruikers', ['gebruiker_id'], ['id'])
    op.add_column('gebruikers', sa.Column('burgerservicenummeer', sa.String(), nullable=True))
    op.drop_constraint('gebruikers_burger_id_fkey', 'gebruikers', type_='foreignkey')
    op.drop_column('gebruikers', 'burger_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gebruikers', sa.Column('burger_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gebruikers_burger_id_fkey', 'gebruikers', 'burgers', ['burger_id'], ['id'])
    op.drop_column('gebruikers', 'burgerservicenummeer')
    op.drop_constraint(None, 'burgers', type_='foreignkey')
    op.drop_column('burgers', 'gebruiker_id')
    # ### end Alembic commands ###
