"""empty message

Revision ID: a8ba4c3c1faa
Revises: 0e9c58c75475
Create Date: 2020-09-29 17:21:07.211528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ba4c3c1faa'
down_revision = '0e9c58c75475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gebruikers', sa.Column('telefoonnummer', sa.String(), nullable=True))
    op.drop_column('gebruikers', 'burgerservicenummeer')
    op.drop_column('gebruikers', 'telefoon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gebruikers', sa.Column('telefoon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gebruikers', sa.Column('burgerservicenummeer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('gebruikers', 'telefoonnummer')
    # ### end Alembic commands ###
    pass
