openapi: 3.0.0
info:
  version: 0.1.0
  title: HHB Gebruiker Service
  description: API voor het beheren van gebruikers van het HHB
  
paths:
  /gebruiker:
    get:
      description: Geeft alle gebruikers van het HHB 
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gebruiker'
        '401':
          description: Unauthorized
        '5XX':
          description: Unexpected error.
    post:
      description: Voeg nieuw gebruiker toe aan het HHB
      security:
        - BearerAuth: []
      parameters:
        - name: telefoonnummer
          required: true
          in: query
          schema:
            type: string
            example: +31612345678
        - name: email
          required: true
          in: query
          schema:
            type: string
            example: henk.poortvliet@sloothuizen.nl
        - name: geboortedatum
          required: true
          in: query
          schema:
            type: string
            format: date
            example: "1980-05-24"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gebruiker'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '5XX':
          description: Unexpected error.
  /gebruiker/{gebruiker_id}:
    parameters:
      - name: gebruiker_id
        in: path
        required: true
        description: Gebruiker id
        schema:
          type : integer
          example: 42
    get:
      description: Geeft specifieke gebruiker uit het HHB
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            ETag:
              schema:
                type: string
              description: Entity tag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gebruiker'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '5XX':
          description: Unexpected error.
    patch:
      description: Update gebruiker gegevens in het HHB
      security:
        - BearerAuth: []
      parameters:
        - name: If-Match
          in: header
          required: true
          schema:
            type: string
            example: "348797893434789789"
        - name: telefoonnummer
          required: false
          in: query
          schema:
            type: string
            example: +31612345678
        - name: email
          required: false
          in: query
          schema:
            type: string
            example: henk.poortvliet@sloothuizen.nl
        - name: geboortedatum
          required: false
          in: query
          schema:
            type: string
            format: date
            example: "1980-05-24"
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gebruiker'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized  
        '404':
          description: Not Found
        '5XX':
          description: Unexpected error.
    delete:
      description: Verwijder gebruiker uit het HHB
      security:
        - BearerAuth: []
      parameters:
        - in: header
          name: If-Match
          schema:
            type: string
          required: true
        - name: gebruiker_id
          in: path
          required: true
          description: Gebruiker id
          schema:
            type : integer
            example: 42
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized          
        '404':
          description: Not Found
        '5XX':
          description: Unexpected error.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Gebruiker:
      type: object
      properties:
        id:
          type: integer
          example: 23
        telefoonnummer:
          type: string
          example: "+31612345678"
        email:
          type: string
          example: henk.poortvliet@sloothuizen.nl
        geboortedatum:
          type: string
          format: date
          example: "1980-05-24"
    Burger:
      type: object
      properties:
        id:
          type: integer
          example: 1337

