openapi: 3.0.0
info:
  version: 0.1.0
  title: HHB Gebruiker Service
  description: API voor het beheren van gebruikers van het HHB
  
paths:
  /gebruiker:
    get:
      description: Geeft alle gebruikers van het HHB 
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Gebruiker_Kort'
        '401':
          description: Unauthorized
        '5XX':
          description: Unexpected error.
    post:
      description: Voeg nieuw gebruiker toe aan het HHB
      security:
        - BearerAuth: []
      parameters:
        - name: burgerservicenummer
          in: query
          required: true
          schema:
            type: string
            example: 0123456789
        - name: kenmerk
          in: query
          schema:
            type: string
            example: 324f44f
        - name: initialen
          in: query
          schema:
            type: string
            example: H. F. G.
        - name: voornaam
          in: query
          schema:
            type: string
            example: Henk
        - name: achternaam
          in: query
          schema:
            type: string
            example: Poortvliet
        - name: toevoeging
          in: query
          schema:
            type: string
            example: van
        - name: telefoon
          in: query
          schema:
            type: string
            example: +31612345678
        - name: email
          in: query
          schema:
            type: string
            example: henk.poortvliet@sloothuizen.nl
        - name: adres
          in: query
          schema:
            type: string
            example: Schoolstraat 1
        - name: postcode
          in: query
          schema:
            type: string
            example: 1234AB
        - name: stad
          in: query
          schema:
            type: string
            example: Sloothuizen
        - name: geboorte_datum
          in: query
          schema:
            type: string
            format: date
            example: "1980-05-24"
        - name: geslacht
          in: query
          schema:
            type: string
            example: Man
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gebruiker'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '5XX':
          description: Unexpected error.
  /gebruiker/{burgerservicenummer}:
    parameters:
      - name: burgerservicenummer
        in: path
        required: true
        description: Gebruiker id
        schema:
          type : integer
    get:
      description: Geeft specifieke gebruiker uit het HHB
      security:
        - BearerAuth: []
      parameters:
        - name: burgerservicenummer
          in: path
          required: true
          schema:
            type: string
            example: 0123456789
      responses:
        '200':
          description: OK
          headers:
            ETag:
              schema:
                type: string
              description: Entity tag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gebruiker'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '5XX':
          description: Unexpected error.
    patch:
      description: Update gebruiker gegevens in het HHB
      security:
        - BearerAuth: []
      parameters:
        - name: If-Match
          in: header
          required: true
          schema:
            type: string
            example: "348797893434789789"
        - name: burgerservicenummer
          in: path
          required: true
          schema:
            type: string
            example: 0123456789
        - name: kenmerk
          in: query
          schema:
            type: string
            example: 324f44f
        - name: initialen
          in: query
          schema:
            type: string
            example: H. F. G.
        - name: voornaam
          in: query
          schema:
            type: string
            example: Henk
        - name: achternaam
          in: query
          schema:
            type: string
            example: Poortvliet
        - name: toevoeging
          in: query
          schema:
            type: string
            example: van
        - name: telefoon
          in: query
          schema:
            type: string
            example: +31612345678
        - name: email
          in: query
          schema:
            type: string
            example: henk.poortvliet@sloothuizen.nl
        - name: adres
          in: query
          schema:
            type: string
            example: Schoolstraat 1
        - name: postcode
          in: query
          schema:
            type: string
            example: 1234AB
        - name: stad
          in: query
          schema:
            type: string
            example: Sloothuizen
        - name: geboorte_datum
          in: query
          schema:
            type: string
            format: date
            example: "1980-05-24"
        - name: geslacht
          in: query
          schema:
            type: string
            example: Man
      responses:
        '200': 
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gebruiker'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized  
        '404':
          description: Not Found
        '5XX':
          description: Unexpected error.
    delete:
      description: Verwijder gebruiker uit het HHB
      security:
        - BearerAuth: []
      parameters:
        - in: header
          name: If-Match
          schema:
            type: string
          required: true
        - name: burgerservicenummer
          in: path
          required: true
          schema:
            type: string
            example: 0123456789
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized          
        '404':
          description: Not Found
        '5XX':
          description: Unexpected error.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Gebruiker_Kort:
      type: object
      properties:
        burgerservicenummer:
          type: integer
          example: 0123456789
        kenmerk:
          type: string
          example: 324f44f
        aanschrijfwijze:
          type: string
          example: H. F. G. van Poortvliet
    Gebruiker:
      type: object
      properties:
        burgerservicenummer:
          type: string
          example: 0123456789
        kenmerk:
          type: string
          example: 324f44f
        initialen:
          type: string
          example: H. F. G.
        voornaam:
          type: string
          example: Henk
        achternaam:
          type: string
          example: Poortvliet
        toevoeging:
          type: string
          example: van
        telefoon:
          type: string
          example: "+31612345678"
        email:
          type: string
          example: henk.poortvliet@sloothuizen.nl
        adres:
          type: string
          example: Schoolstraat 1
        postcode:
          type: string
          example: 1234AB
        stad:
          type: string
          example: Sloothuizen
        geboorte_datum:
          type: string
          format: date
          example: "1980-05-24"
        geslacht:
          type: string
          example: Man