apiVersion: v1
kind: ConfigMap
metadata:
  name: hhb-dex-config
  namespace: ${NAMESPACE}
  labels:
    name: hhb-dex-config
data:
  config.yaml: |-
    issuer: http://dex.${HHB_HOST}
    storage:
      config:
        file: ':memory:'
        inCluster: true
      type: sqlite3
    logger:
      level: info
    web:
      http: 0.0.0.0:5556
    oauth2:
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    staticClients:
      - id: huishoudboekje
        name: Huishoudboekje Schaalbaar
        redirectURIs:
          - "http://${HHB_HOST}/api/oidc_callback"
          - "https://${HHB_HOST}/api/oidc_callback"
        secret: ${HHB_SECRET}
    staticPasswords:
    - userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
      username: "koen@openweb.nl"
      email: "koen@openweb.nl"
      hash: "$2a$12$0hTm/oGiy/NWrtlXzP3diuo6iRKDgl2JvTPCGI2PLSAb84q0JGnxa"
    enablePasswordDB: true
    expiry:
      idTokens: 168h