apiVersion: apps/v1
kind: Deployment
metadata:
  name: hhb-dex
  namespace: ${NAMESPACE}
  labels:
    name: hhb-dex
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hhb-dex
  template:
    metadata:
      labels:
        name: hhb-dex
    spec:
      containers:
        - name: hhb-dex
          image: 'quay.io/dexidp/dex:v2.24.0'
          imagePullPolicy: "IfNotPresent"
          command:
            - /usr/local/bin/dex
            - serve
            - /etc/dex/cfg/config.yaml
          ports:
            - name: http
              containerPort: 5556
              protocol: TCP
#          resources:
#            limits:
#              cpu: '1'
#              memory: 1Gi
#            requests:
#              cpu: 100m
#              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - name: dex-config-volume
              mountPath: /etc/dex/cfg
      volumes:
        - name: dex-config-volume
          configMap:
            name: hhb-dex-config