apiVersion: v1
kind: Service
metadata:
  name: hhb-huishoudboekjeservice
  labels:
    name: hhb-huishoudboekjeservice
  namespace: ${NAMESPACE}
spec:
  type: ClusterIP
  selector:
    name: hhb-huishoudboekjeservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
