---
# Build docker images
build-docker-images:
  retry:
    max: 2
    when: script_failure
  stage: build
  image: registry.gitlab.com/commonground/huishoudboekje/review-app-deployer:latest
  needs: []
  tags:
    - cg
    - shell
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    CYPRESS_INSTALL_BINARY: "0"
  script:
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - mkdir -p $DOCKER_CONFIG && echo $DOCKER_AUTH_CONFIG > $DOCKER_CONFIG/config.json
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - sh ./scripts/docker-build-and-push.sh
  only:
    - branches@commonground/huishoudboekje/app-new
