# This template requires the following:
#   variables:
#      APP_NAME: <the name of the application/directory>
.build:
  stage: build
  needs: []
  tags:
    - cg
    - shell
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$APP_NAME:$IMAGE_TAG ./$APP_NAME
  after_script:
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/$APP_NAME:$IMAGE_TAG

build-python-postgres:
  extends: .build
  variables:
    APP_NAME: python-postgres
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$APP_NAME:$IMAGE_TAG - < test.dockerfile
  only:
    - branches@commonground/huishoudboekje/app-new

build-frontend:
  variables:
    APP_NAME: frontend
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new

build-backend:
  variables:
    APP_NAME: backend
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new

# This template requires the following:
#   variables:
#      APP_NAME: <the name of the application>
#      APP_DIRECTORY: <the directory in services that contains the application>
.build-service:
  extends: .build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/$APP_NAME:$IMAGE_TAG -f ./services/$APP_DIRECTORY/Dockerfile ./services

build-huishoudboekje-service:
  variables:
    APP_NAME: huishoudboekje-service
    APP_DIRECTORY: huishoudboekje_service
  extends: .build-service
  only:
    - branches@commonground/huishoudboekje/app-new

build-organisatie-service:
  variables:
    APP_NAME: organisatie-service
    APP_DIRECTORY: organisatie_service
  extends: .build-service
  only:
    - branches@commonground/huishoudboekje/app-new

build-bank-transactie-service:
  variables:
    APP_NAME: bank-transactie-service
    APP_DIRECTORY: bank_transactie_service
  extends: .build-service
  only:
    - branches@commonground/huishoudboekje/app-new

build-grootboek-service:
  variables:
    APP_NAME: grootboek-service
    APP_DIRECTORY: grootboek_service
  extends: .build-service
  only:
    - branches@commonground/huishoudboekje/app-new

build-docs:
  variables:
    APP_NAME: docs
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new

build-helm:
  stage: build
  needs: []
  tags:
    - cg
    - docker
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  before_script:
    - helm repo add stable "https://charts.helm.sh/stable"
    - helm repo add zalando-operator "https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator"
    - helm repo update
  script:
    - helm dependency build helm/charts/huishoudboekje
    - mkdir -p helm/charts/huishoudboekje/charts/medewerker-frontend/theme
    - cp -r frontend/theme/sloothuizen/ helm/charts/huishoudboekje/charts/medewerker-frontend/theme
    - helm package -d huishoudboekje helm/charts/huishoudboekje
  artifacts:
    name: huishoudboekje
    expose_as: 'Huishoudboekje Helm Repository'
    paths:
      - "huishoudboekje/"
    expire_in: 1 week
  only:
    - branches@commonground/huishoudboekje/app-new
