.retry: &retry
  retry:
    max: 2
    when: script_failure

.build-docker-images: &build-docker-images
  <<: *retry
  stage: build
  image: registry.gitlab.com/commonground/huishoudboekje/review-app-deployer:latest
  needs: [ ]
  services:
    - docker:20.10.22-dind
  tags:
    - cg
    - docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    CYPRESS_INSTALL_BINARY: "0"
  script:
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - mkdir -p $DOCKER_CONFIG && echo $DOCKER_AUTH_CONFIG > $DOCKER_CONFIG/config.json
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - sh ./scripts/docker-build-and-push.sh

.build-storybook: &build-storybook
  <<: *retry
  stage: build
  image: registry.gitlab.com/commonground/huishoudboekje/review-app-deployer:latest
  needs: [ ]
  services:
    - docker:20.10.22-dind
  tags:
    - cg
    - docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - mkdir -p $DOCKER_CONFIG && echo $DOCKER_AUTH_CONFIG > $DOCKER_CONFIG/config.json
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/storybook:$IMAGE_TAG --build-arg "DOCKER_PROXY=$DOCKER_PROXY" --file=./frontend/storybook.Dockerfile frontend
    - docker push $CI_REGISTRY_IMAGE/storybook:$IMAGE_TAG

# Build the Storybook docker image
build-storybook:
  <<: *build-storybook
  only:
    - branches@commonground/huishoudboekje/app-new
  except:
    - master
    - acceptance

# Build docker images with default tag ("branchName-commitSha").
# build-images-dev:
#   <<: *build-docker-images
#   only:
#     - branches@commonground/huishoudboekje/app-new

# Build docker images with the name of the tag as the image tag.
build-tagged-images:
  <<: *build-docker-images
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
  only:
    - tags
  except:
    - branches@commonground/huishoudboekje/app-new


build-docker-images-parallel:
  stage: build
  image: registry.gitlab.com/commonground/huishoudboekje/review-app-deployer:latest
  needs: [ ]
  services:
    - docker:20.10.22-dind
  tags:
    - cg
    - docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    CYPRESS_INSTALL_BINARY: "0"
  script:
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - mkdir -p $DOCKER_CONFIG && echo $DOCKER_AUTH_CONFIG > $DOCKER_CONFIG/config.json
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/$NAME:$IMAGE_TAG $DOCKERATTRIBUTES
    - docker push $CI_REGISTRY_IMAGE/$NAME:$IMAGE_TAG
  only:
    refs:
      - branches@commonground/huishoudboekje/app-new
    # changes:
    #   - $DIR
  parallel:
    matrix:
      - NAME: frontend
        DOCKERATTRIBUTES: "./frontend"
        DIR: ./frontend
      - NAME: backend
        DOCKERATTRIBUTES: "./backend"
        DIR: ./backend
      - NAME: backendburgers
        DOCKERATTRIBUTES: "./backend-burgers"
        DIR: ./backend-burgers
      - NAME: unleashservice
        DOCKERATTRIBUTES: "./services/unleashservice"
        DIR: ./services/unleashservice
      - NAME: postadressenservice
        DOCKERATTRIBUTES: "./services/postadressenservice"
        DIR: ./services/postadressenservice
      - NAME: alarmenservice
        DOCKERATTRIBUTES: "./services/alarmenservice"
        DIR: ./services/alarmenservice
      - NAME: signalenservice
        DOCKERATTRIBUTES: "./services/signalenservice"
        DIR: ./services/signalenservice
      - NAME: authservice
        DOCKERATTRIBUTES: "./services/authservice"
        DIR: ./services/authservice
      - NAME: banktransactieservice
        DOCKERATTRIBUTES: "--file=./services/bank_transactie_service/Dockerfile services"
        DIR: ./services/banktransactieservice
      - NAME: grootboekservice
        DOCKERATTRIBUTES: "--file=./services/grootboek_service/Dockerfile services"
        DIR: ./services/grootboekservice
      - NAME: huishoudboekjeservice
        DOCKERATTRIBUTES: "--file=./services/huishoudboekje_service/Dockerfile services"
        DIR: ./services/huishoudboekjeservice
      - NAME: logservice
        DOCKERATTRIBUTES: "--file=./services/log_service/Dockerfile services"
        DIR: ./services/logservice
      - NAME: organisatieservice
        DOCKERATTRIBUTES: "--file=./services/organisatie_service/Dockerfile services"
        DIR: ./services/organisatieservice
      - NAME: rapportageservice
        DOCKERATTRIBUTES: "--file=./services/rapportage_service/Dockerfile services"
        DIR: ./services/rapportageservice

