#.namespace-review: &namespace-review
#  variables:
#    NAMESPACE: "hhb-$CI_COMMIT_REF_SLUG"
#
#.build:
#  stage: build
#  needs: []
#  retry:
#    max: 2
#    when: script_failure
#  variables:
#    DOCKER_TLS_CERTDIR: "/certs"
#    CYPRESS_INSTALL_BINARY: "0"
#  script:
#    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
#    - mkdir -p $DOCKER_CONFIG && echo $DOCKER_AUTH_CONFIG > $DOCKER_CONFIG/config.json
#    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
#    - sh ./scripts/docker-build-and-push.sh
#    - sh ./k8s/build.sh
#  artifacts:
#    paths:
#      - k8s/dist
#  only:
#    - branches@commonground/huishoudboekje/app-new
#
#build-review:
#  <<: *namespace-review
#  extends:
#    - .build
#  tags:
#    - cg
#    - shell
#  only:
#    - branches@commonground/huishoudboekje/app-new

#build-fork:
#  <<: *namespace-review
#  extends:
#    - .build
#  image: docker:19.03.13
#  services:
#  - docker:19.03.13-dind
#  tags:
#    - docker
#  except:
#    - branches@commonground/huishoudboekje/app-new
#  before_script:
#    - apk add --no-cache git make gettext-base