build:
  stage: build
  needs: []
  tags:
    - cg
    - shell
  variables:
    IMAGE_PREFIX: "$CI_REGISTRY/$CI_PROJECT_PATH/"
    DOCKER_PROXY: "gitlab.com/commonground/huishoudboekje/dependency_proxy/containers/"
  before_script:
    - export COMPONENT_TAG=$(git describe --long --all | sed 's!heads/!!')
    - export COMPONENT_COMMIT_HASH=$(git describe --always --abbrev=0 --match "NOT A TAG")
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY <<< $CI_JOB_TOKEN
  script:
    - docker-compose build --build-arg DOCKER_PROXY="$DOCKER_PROXY" --parallel --pull
    - docker-compose push
  only:
    - branches@commonground/huishoudboekje/app-new

build-helm:
  stage: build
  needs: []
  tags:
    - cg
    - docker
  image:
    name: gitlab.com/commonground/huishoudboekje/dependency_proxy/containers/alpine/helm:latest
    entrypoint: [""]
  before_script:
    - helm repo add stable "https://charts.helm.sh/stable"
    - helm repo add zalando-operator "https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator"
    - helm repo update
  script:
    - helm dependency build helm/charts/huishoudboekje
    - mkdir -p helm/charts/huishoudboekje/charts/medewerker-frontend/theme
    - cp -r frontend/theme/sloothuizen/ helm/charts/huishoudboekje/charts/medewerker-frontend/theme
    - helm package -d huishoudboekje helm/charts/huishoudboekje
  artifacts:
    name: huishoudboekje
    expose_as: 'Huishoudboekje Helm Repository'
    paths:
      - "huishoudboekje/"
    expire_in: 1 week
  only:
    - branches@commonground/huishoudboekje/app-new
