.build:
  tags:
    - cg
    - shell
  script:
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$APP_NAME:$IMAGE_TAG ./$DIRECTORY
    - docker push $CI_REGISTRY_IMAGE/$APP_NAME:$IMAGE_TAG

# Build Frontend
build-frontend:
  stage: build
  variables:
    APP_NAME: frontend
    DIRECTORY: frontend
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new

# Build Backend
build-backend:
  stage: build
  variables:
    APP_NAME: backend
    DIRECTORY: backend
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new

# Build Huishoudboekje Service
build-huishoudboekje-service:
  stage: build
  variables:
    APP_NAME: huishoudboekje-service
    DIRECTORY: huishoudboekje-service
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new

# Build Docs
build-docs:
  stage: build
  variables:
    APP_NAME: docs
    DIRECTORY: docs
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new

build-helm:
  tags:
    - cg
    - docker
  stage: build
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  before_script:
    - helm repo add stable "https://kubernetes-charts.storage.googleapis.com"
    - helm repo add zalando-operator "https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator"
    - helm repo add zalando-operator-ui "https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator-ui"
    - helm repo update
  script:
    - helm dependency build helm/charts/huishoudboekje
    - mkdir -p helm/charts/huishoudboekje/charts/medewerker-frontend/theme
    - cp -r frontend/theme/sloothuizen/ helm/charts/huishoudboekje/charts/medewerker-frontend/theme
    - helm package -d huishoudboekje helm/charts/huishoudboekje
  artifacts:
    name: huishoudboekje
    expose_as: 'Huishoudboekje Helm Repository'
    paths:
      - "huishoudboekje/"
    expire_in: 1 week

