.build:
  script:
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$APP_NAME:$IMAGE_TAG ./$DIRECTORY
    - docker push $CI_REGISTRY_IMAGE/$APP_NAME:$IMAGE_TAG

# Build Frontend
build-frontend:
  stage: build
  image: docker
  variables:
    APP_NAME: frontend
    DIRECTORY: frontend
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new

# Build Backend
build-backend:
  stage: build
  image: docker
  variables:
    APP_NAME: backend
    DIRECTORY: backend
  extends: .build
  only:
    - branches@commonground/huishoudboekje/app-new
