build:
  stage: build
  needs: []
  image: docker:19.03.13

  services:
  - docker:19.03.13-dind
  tags:
    - cg
    - docker
#    - shell
  retry:
    max: 2
    when: script_failure
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_PREFIX: "$CI_REGISTRY/$CI_PROJECT_PATH/"
    CYPRESS_INSTALL_BINARY: "0"
  before_script:
    - apk add --no-cache git docker-compose
    - export COMPONENT_TAG=$(git describe --long --all | sed 's!heads/!!')
    - export COMPONENT_COMMIT_HASH=$(git describe --always --abbrev=0 --match "NOT A TAG")
    - export DOCKER_CONFIG=/tmp/docker-config-$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
#    - docker login -u "$CI_DEPENDENCY_PROXY_USER" --password-stdin "$CI_DEPENDENCY_PROXY_SERVER" <<< "$CI_DEPENDENCY_PROXY_PASSWORD"
  script:
#    - env | sort | grep DEPENDENCY
#    - docker-compose build --build-arg DOCKER_PROXY="${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/" --parallel --pull
    - docker-compose build --parallel
    - docker-compose push
  only:
    - branches@commonground/huishoudboekje/app-new

build-helm:
  stage: build
  needs: []
  tags:
    - cg
    - docker
  retry:
    max: 2
    when: script_failure
  image:
    name: ${DOCKER_PROXY}alpine/helm:latest
    entrypoint: [""]
  before_script:
    - helm repo add stable "https://charts.helm.sh/stable"
    - helm repo add zalando-operator "https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator"
    - helm repo update
  script:
    - helm dependency build helm/charts/huishoudboekje
    - mkdir -p helm/charts/huishoudboekje/charts/medewerker-frontend/theme
    - cp -r frontend/theme/sloothuizen/ helm/charts/huishoudboekje/charts/medewerker-frontend/theme
    - helm package -d huishoudboekje helm/charts/huishoudboekje
  artifacts:
    name: huishoudboekje
    expose_as: 'Huishoudboekje Helm Repository'
    paths:
      - "huishoudboekje/"
    expire_in: 1 week
  only:
    - branches@commonground/huishoudboekje/app-new
