---
# only a PersistentVolumeClaim, no PersistentVolume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hhb-database-volumeclaim
  labels:
    name: hhb-database-volumeclaim
spec:
  storageClassName: ${STORAGECLASSNAME}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
