"""gebruiker_id is a string

Revision ID: a6ffe07c1d5d
Revises: 7381a56f87fa
Create Date: 2021-01-21 12:38:35.425900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ffe07c1d5d'
down_revision = '7381a56f87fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gebruikersactiviteiten', 'gebruiker_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gebruikersactiviteiten', 'gebruiker_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
