"""add uuid

Revision ID: fafaeb098f1f
Revises: a6ffe07c1d5d
Create Date: 2023-05-19 10:17:15.585993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID
import uuid as GEN_UUID

# revision identifiers, used by Alembic.
revision = 'fafaeb098f1f'
down_revision = 'a6ffe07c1d5d'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        'gebruikersactiviteiten',
        sa.Column(
            'uuid',
            UUID(),
            unique=True,
            index=True
        )
    )

    connection = op.get_bind()
    content = connection.execute(
        sa.text(f"SELECT id FROM gebruikersactiviteiten"))

    for row in content:
        connection.execute(sa.text(
            f"UPDATE gebruikersactiviteiten SET uuid='{str(GEN_UUID.uuid4())}' WHERE id = '{row['id']}'"))

    op.alter_column('gebruikersactiviteiten', 'uuid', nullable=False,
                    server_default=sa.text("'{}'".format(str(GEN_UUID.uuid4()))))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gebruikersactiviteiten', 'uuid')
    # ### end Alembic commands ###
